### ISSUE TITLE
Add Segwit addresses

### ISSUE THREAD

**Issue by i-rme** [iancoleman/bip39#100]
Add the possibilty to display the segwit addresses associated to a seed.

**Comment by iancoleman** [comment]
Can you please confirm what this means?

The BIP49 tab generates segwit addresses, and there's an option in the BIP32 tab to generate segwit addresses. If this issue is for some other segwit feature, please give more detail.

**Comment by i-rme** [comment]
I was not able to generate a Segwit address from his private key.

**Comment by iancoleman** [comment]
Please be clearer about the steps taken and what the expected result is vs the actual result seen.

**Comment by i-rme** [comment]
Sorry, I didn't notice the BIP49 tab. There is no problem. Closed.

**Comment by 7flash** [comment]
@iancoleman "and there's an option in the BIP32 tab to generate segwit addresses"
Where is it?

**Comment by iancoleman** [comment]
It's been removed from the bip32 tab because it's replaced by the bip141 tab (which is for general segwit derivation paths). bip32 is for general derivation paths of p2pkh addresses and bif141 is for general derivation paths of segwit addresses.
