### ISSUE TITLE
QR code missing accents

### ISSUE THREAD

**Issue by iancoleman** [iancoleman/bip39#101]
Continuing from https://github.com/iancoleman/bip39/issues/97#issuecomment-326841251

> I also noticed that if I use the QR code in bip39 to capture the words, words like "álbum" would be "album" with no "´"

**Comment by Zwilla** [comment]
mtw and mew uses this function: hd.bip39.validateMnemonic(mnemonic)

I have compared the wordlists ES, they are 100% identical.

But I found some differences. I will inspect it these days.

@iancoleman: I have nearly finished my work on the converter. If you have time to take a look at:
https://mytokenwallet.com/bip39.html and find some of my implemented work cool, let me know I will merge it into your repro.

* Translation now works fine. At moment only spanish is finished, if you like it, I will complete the other also and push my work to yours.

**Comment by Zwilla** [comment]
I have found a solution and will rewrite it to implement in to the converter.
Many test I made and now after very intensive research I have found a working solution to show a 100% working QR-Code which will be readable from every qr-code reader.

I will let you know, that it does not depends on the correction level, it depends on the lib which is at moment build in.
Have a nice Sunday

zwilla

**Comment by Zwilla** [comment]
Here is my finished work.
https://mytokenwallet.com/bip39.html

Please test the qr-code now. 
If you also have now no trouble with the generated code, let me know, that I can merge my work into yours.

thx
zwilla

**Comment by iancoleman** [comment]
See https://github.com/iancoleman/bip39/commit/9225b805d6674a45804d96b66ca4b77ba9d52c73
