### ISSUE TITLE
Copay and this bip39 tool

### ISSUE THREAD

**Issue by TheCryptek** [iancoleman/bip39#124]
Is it possible to make the tool generate BCH - Bitcoin Cash address that starts with C instead of 1 so that way I can use my address with Copay?

**Comment by iancoleman** [comment]
Should be possible.

Some technical details for my own future reference:

https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests

> we will use a distinct version byte for BCH addresses. The version byte is set to 28 for p2pkh addresses and 40 for p2sh addresses.
>
> If you wish to translate a BCH address with the current format to the new address convention, you can use our new Address Translator tool: https://bitpay.github.io/address-translator/

**Comment by TheCryptek** [comment]
Well I was hoping to not have to use the translator. I used it once for shapeshifters bch address but if I knew how I'd code it in myself and make a pull request

**Comment by TheCryptek** [comment]
@iancoleman just let me know if you can do it. If I knew how, I would.

**Comment by iancoleman** [comment]
See https://github.com/iancoleman/bip39/commit/fe8f2d140d9c9e260ebeab7135aa5197b27df406 - Allow BitPay address format for bitcoin cash

* Open v0.2.8 or greater of the tool
* Generate random mnemonic (or enter your own)
* Select bitcoin cash
* Above the addresses table will be a checkbox to use bitpay-style addresses, which when checked will generate addresses starting with 'C' and are cross compatible with the bitpay address translator linked above.
