### ISSUE TITLE
use new xpub/xprv prefixes for Segwit BIP49

### ISSUE THREAD

**Issue by prusnak** [iancoleman/bip39#125]
Please use the following constants for BIP49 xpub/xprv prefixes as per http://docs.electrum.org/en/latest/seedphrase.html#list-of-reserved-numbers

Bitcoin:

0x049d7878 yprv
0x049d7cb2 ypub

Bitcoin Testnet:

0x044a5262 upub
0x044a4e28 uprv

Litecoin:

0x01b26ef6 Mtub
0x01b26792 Mtpv

This will assure that user does not accidentally imports BIP49 xpub to BIP44 watch only wallet.

**Comment by iancoleman** [comment]
Thanks for this.

See https://github.com/iancoleman/bip39/commit/93c3ef47579733040dbc6eec865b528d1ca49911 - Use correct prefixes for xprv/xpub with segwit

**Comment by prusnak** [comment]
Love it! Thanks
