### ISSUE TITLE
Ethereum keys generated differently in different tools

### ISSUE THREAD

**Issue by oniony** [iancoleman/bip39#127]
If I use the [Coinomi tool](http://coinomi.com/recovery-phrase-tool.html) to generate a random phares (e.g. `badge unit ordinary someone top virtual repair prevent blast insect virtual trip polar cement onion`) and then paste this into your tool I get the same keys for Bitcoin (key starting `xprv`) but in the Coinomi tool when I switch to Ethereum I get a key starting `wM5u`: your tool however continues to show the same key as for Bitcoin.

Do you know which is correct and why the algorithm might be different for Ethereum?

**Comment by oniony** [comment]
I believe this might be a question for Coinomi as they seem to be a fork of your tool.

**Comment by iancoleman** [comment]
Related issue posted the next day:

https://github.com/iancoleman/bip39/issues/128

**Comment by thinkloop** [comment]
@oniony would you mind linking to any related thread at coinomi.

**Comment by oniony** [comment]
They have no issue tracker on their repo so I have up. Now I can generate the keys I am less terrified.
