### ISSUE TITLE
Stellar (XLM) support

### ISSUE THREAD

**Issue by bartekn** [iancoleman/bip39#130]
Will you accept a PR adding support for Stellar? I can work on this.

**Comment by iancoleman** [comment]
Most probably yes, so long as it's not too difficult to audit the changes in the PR. I don't know anything about stellar, but if it's reasonably similar to how bitcoin works (which I assume it is) then it shouldn't be any problem.

**Comment by vladare** [comment]
This link https://github.com/chatch/stellar-hd-wallet does help you to add support for the Stellar

**Comment by iancoleman** [comment]
This is great! Hopefully someone from the Stellar community can submit a pull request to add it to this tool.

**Comment by dgobaud** [comment]
@bartekn @iancoleman Yes please add Stellar support!

**Comment by darocha** [comment]
Yes please add Stellar support!

**Comment by wilsoff** [comment]
@bartekn, it would be great if you could help add Stellar please.

Another resource that might help:
https://github.com/stellar-fox/redshift

**Comment by iancoleman** [comment]
the stellar community can add their coin by submitting a pull request.
