### ISSUE TITLE
instructions to replicate seed from own source of entropy with different tool

### ISSUE THREAD

**Issue by onpars** [iancoleman/bip39#131]
I don't like to use the browser's RandomSource.getRandomValues(). Why? Because I don't get to see it. And it might be worse than /dev/random. (Strange things happen - see Debian SSL debacle so better be safe than sorry.)

Is it possible to,
1) read good entropy from let's say /dev/random [1]
2) feed to iancoleman/bip39
3) refeed the same entropy to python-trezor's [`words = mnemonic.Mnemonic('english').to_mnemonic(entropy)`](https://github.com/trezor/python-trezor/blob/master/tools/mnemonic_check.py#L66) [2]

Why? To verify the same entropy and algorithm deterministically generates the same seed. The same algorithm with different implementations ending up with the same result would be a nice test, no? :)

Could you provide such instructions please?

[1] or better/combined as suggested
[2] gladly any other appropriate alternative tool(s)

**Comment by iancoleman** [comment]
It is possible.

1. Select 'Supply my own source of entropy'
1. Paste entropy (it's easy to use test entropy from [the official bip39 test vectors](https://github.com/trezor/python-mnemonic/blob/master/vectors.json) just to test it out).
1. Ensure 'Mnemonic Length' is set to 'Use Raw Entropy' (which is the default setting)
1. The mnemonic in this tool should match the mnemonic in the test vector.

To encode entropy from /dev/random as hex and thus use in this tool or the `python-mnemonic` library, use the following in bash (or [any of these answers](https://stackoverflow.com/q/34328759))

```
hexdump -n 16 -e '4/4 "%08X" 1 "\n"' /dev/random
```

But if you trust /dev/random then you can [trust the browser](https://github.com/iancoleman/bip39/blob/f487fea9b8b37642a3940be63129d9835eb77229/src/js/index.js#L412). I recommend using a well shuffled deck of cards if you don't trust /dev/random.

See also 'Entropy Notes' ([webpage](https://iancoleman.io/bip39/#entropy-notes) and / or [source code](https://github.com/iancoleman/bip39/blob/f487fea9b8b37642a3940be63129d9835eb77229/src/index.html#L666-L698)) for more detail about not screwing up entropy for mnemonics.
