### ISSUE TITLE
question about alternative tools

### ISSUE THREAD

**Issue by mr10008** [iancoleman/bip39#133]
Thanks for a nice tool.
Question here: on your page https://iancoleman.io/bip39/ under Alternative tools you mention this one https://bip32jp.github.io/english/ and say: "(ie not consumer wallets)" 
Can you clarify what you mean by 'not consumer wallets'?

**Comment by iancoleman** [comment]
'not consumer wallets' means it's not something you recommend to a newcomer. I perceive a consumer wallet to be something where if your friend wants to receive some bitcoin from you, you might say "use [insert consumer wallet name eg mycellium] to receive the coins I'm about to send you" - that's a consumer wallet.

If alternative tools included consumer wallets it would be a very long list indeed (ie all wallets which use a mnemonic seed) and I don't think that's useful or really considered 'alternatives' to this tool, which is more focused on engineering / development / advanced users.
