### ISSUE TITLE
bip39

### ISSUE THREAD

**Issue by silvanamiller** [iancoleman/bip39#138]
I have a wallet at blockchain but forgot my second password.
I used the bip39 made by Ian Coleman and as instructed entered my 12 word mnemonic/seed.  It successfully generated all kinds of addresses, but my address was not listed to get my private key.  How can I enter my address and my 12 words to find the private key?

**Comment by iancoleman** [comment]
General support is not provided here.

Please ask for support from your wallet provider or the bitcoin community.

If you feel this issue has been incorrectly closed, please reopen it with specific details of the feature or bug to be investigated and how it should lead to changes being implemented in this tool.

**Comment by silvanamiller** [comment]
What I really need to know is that I used your bip39.  I entered the 12
mnemonics and generated over 10,000 addresses, but the address I used was
not one of them.  Is there a way that I can enter the mnemonics as normal,
but then enter my address to find my private key?  Or is there a program
out there that will find my private key?  blockchain.info support is of no
help.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
