### ISSUE TITLE
Was not able to duplicate wallet addresses for Trezor

### ISSUE THREAD

**Issue by pahenator** [iancoleman/bip39#139]
Was not able to duplicate wallet addresses for Trezor event wrote all seeds correctly and copied BIP32 path from Trezor site

**Comment by iancoleman** [comment]
General support is not provided here.

Please ask for support from your wallet provider or the bitcoin community.

If you feel this issue has been incorrectly closed, please reopen it with specific details of the feature or bug to be investigated and how it should lead to changes being implemented in this tool.
