### ISSUE TITLE
Add BIP-38 Support

### ISSUE THREAD

**Issue by praeluceo** [iancoleman/bip39#140]
Feature Request: When generating Derived private keys, add the option to derive and then apply a BIP38 passphrase for security. (Obviously this would add rendering time for each key, but would still be faster than performing it incrementally on each key).

**Comment by iancoleman** [comment]
I like this suggestion.

Probably will use the bitcoinjs/bip38 library - https://github.com/bitcoinjs/bip38

**Comment by praeluceo** [comment]
If you do, it seems that from my experience (see https://github.com/cantonbecker/bitcoinpaperwallet/issues/32) that it is also helpful to generate the compressed public key in addition to the uncompressed public key, or else to generate the uncompressed private key (generating the private 5... key not only the K... or L... key).

When one sweeps a BIP38 encrypted wallet into a client such as Mycelium or Samurai, the public key that gets imported is the public key from the uncompressed version of the private key.

**Comment by iancoleman** [comment]
See

https://github.com/iancoleman/bip39/commit/0f0a888e13ed565a95454fa7a1e46d5db0daf55a - Add bitcoinjs-bip38-2.0.2 library

https://github.com/iancoleman/bip39/commit/cc61ec30c5647b08cf11d918a6656cfc922e4586 - Encrypt private keys with BIP38

https://github.com/iancoleman/bip39/commit/0b39e9dca79f71d898693d5cb93b6a1d1e0372f6 - Add BIP38 interface elements

https://github.com/iancoleman/bip39/commit/e21e32da3199b9c8471bb44707f1f228a62f339b - Add BIP38 test

Released with 0.3.3

Thanks again for the suggestion and tips about uncompressed keys.
