### ISSUE TITLE
add qtum(QTUM)

### ISSUE THREAD

**Issue by jingtian8** [iancoleman/bip39#141]
Hi, now ledger nano s wallet support QTUM, please add QTUM
regards

**Comment by iancoleman** [comment]
Please ask the QTUM community to submit a pull request for this.

For an example of what is required, see the commit where nubits network was added. https://github.com/iancoleman/bip39/commit/8dd28f2cff4e1f673f4aa7adc93a7254de72a297

**Comment by iancoleman** [comment]
Closed in favour of https://github.com/iancoleman/bip39/pull/144
