### ISSUE TITLE
is the entered seed "saved" to the usb file?

### ISSUE THREAD

**Issue by ahmedahmedov** [iancoleman/bip39#145]
When opening the standalone website from a usb flash drive, can I be sure that none of the info is saved to the flash drive?

**Comment by iancoleman** [comment]
In theory yes you can be sure no info is saved to the flash drive, but in reality it depends on the operating system and browser being used.

The things to be aware of:

* the app does not make use of html5 file api so the app itself does not use any file system. It's entirely in memory.
* the browser may cache content, for example: open the standalone page, generate a mnemonic, navigate to a different page by typing one the address bar, press the back button on the browser - the mnemonic will still exist meaning it must be stored in cache somewhere (presumably memory, but if swap is being used etc...)

I think there is no way info can be saved to file permanently, but again I want to say it depends on the particular os / browser.

**Comment by ahmedahmedov** [comment]
Thanks for the explanation. I was worried after stumbling upon this thread in Reddit - https://www.reddit.com/r/TREZOR/comments/7jaqct/should_i_be_paranoid_seed_entered_on_a_live/?st=jb4ue757&sh=25444211
