### ISSUE TITLE
Generating addresses for BTG does not seem to work

### ISSUE THREAD

**Issue by mr10008** [iancoleman/bip39#147]
Thanks for a great tool!

Just playing with it and trying to see if the addresses generated by it for different coins correspond to what I'm getting in my Ledger Nano. Looks OK except for BTG that is supposed to have Coin code 156 and not 0 and addresses starting on letter A - this is under BIP 44. 

Under BIP 49 the addresses start with A so that's OK. but the Coin code is still 0 - why?

**Comment by iancoleman** [comment]
Seems like there are a few different types of bitcoin gold:

From [ledger-wallet-chrome/networks.coffee](https://github.com/LedgerHQ/ledger-wallet-chrome/blob/30d62f1a3de940a9e3bffb61ca3bd9851b33739b/app/src/bitcoin/networks.coffee#L247)

```
bitcoin_gold_unsplit:
bip44_coin_type: '0'

bitcoin_gold_split:
bip44_coin_type: '156'

bitcoin_gold_unsplit_segwit:
bip44_coin_type: '0'

bitcoin_gold_split_segwit:
bip44_coin_type: '156'
```

If someone from the bitcoingold community can resolve this I'd be happy to include the changes, but altcoins are not something I am tracking or updating personally.

**Comment by iancoleman** [comment]
If this is an issue for btg users the btg community can submit a pull request fixing it.
