### ISSUE TITLE
XEM support

### ISSUE THREAD

**Issue by gtsq** [iancoleman/bip39#148]
Hi. Thanks for a great tool. XEM has recently been added to Trezor but as far as I can tell there's no way of extracting XEM private keys from the 24 word Trezor seed. 

No other XEM wallets support seeds and there's no way to display a private key on the Trezor so no Trezor, no XEM. Is adding support for XEM a possibility? 

Trezor support pointed me to this tool when I asked them, but as far I can tell it can't be done as is. I might be missing something obvious.

Thanks a lot.

**Comment by iancoleman** [comment]
XEM is not currently supported by this tool but it may be added if someone from that community submits a pull request including it in the list of coins.

An example of what is required to add a new coin can be seen in https://github.com/iancoleman/bip39/commit/66419cf39c76e60f1b7db419dd1d88f7b221cdbb

**Comment by iancoleman** [comment]
The xem community can add their coin by submitting a pull request.
