### ISSUE TITLE
Bitcoin Diamond (BCD) Support

### ISSUE THREAD

**Issue by Joohansson** [iancoleman/bip39#150]
Bitcoin Diamond was forked from bitcoin on block #495866 (2017-11-24).
http://www.btcd.io

It seems to be up and running but I don't know how legitimate it is.
However I had a significant value of btc during the fork in a Ledger Nano. If possible, I would like to get access to the forked BCD coins. Maybe through this tool if support is added?
Current bcd price is 0.0022btc but each btc before the fork corresponds to 10 bcd.

I don't think Ledger will support this coin any time soon like they did with BCH and BTG.

**Comment by iancoleman** [comment]
If someone from the BCD community is willing to add the coin via a pull request I am happy to review it.

An example of what is needed can be seen in https://github.com/iancoleman/bip39/commit/66419cf39c76e60f1b7db419dd1d88f7b221cdbb

**Comment by iancoleman** [comment]
The bcd community can add their coin by submitting a pull request adding their coin.
