### ISSUE TITLE
BIP-84 support

### ISSUE THREAD

**Issue by prusnak** [iancoleman/bip39#151]
Please add support for BIP-84 : https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki

It is basically a version of BIP-44 for P2WPKH addresses (similarly as BIP-49 is a version of BIP-44 for P2WPKH-in-P2SH.

Private keys should start with zprv and public keys with zpub.

Magic constants are here: https://github.com/spesmilo/electrum/blob/0a648e2b1cdb7852d80c0626c62984ef01c1c7e9/lib/bitcoin.py#L50

**Comment by iancoleman** [comment]
Thanks for this.

See https://github.com/iancoleman/bip39/commit/4e9b492ca4e1f90b985cfc2da94bddc60a36e386

**Comment by prusnak** [comment]
Great!
