### ISSUE TITLE
Recommended segwit BIP?

### ISSUE THREAD

**Issue by drudru** [iancoleman/bip39#157]
Hi,

Thanks for this project.

I think a lot of people are going to start switching for segwit txns. 

Currently there are the tabs which allow you to choose the various BIPS. I think it would be great if there was a recommendation for new users as to which BIP and settings to use.

**Comment by iancoleman** [comment]
Which BIP a user should go with depends and changes on the needs of each particular user.

I see your point, it's not easy to just pick the tool up and know what to do. There's a lot of links to 'more reading' throughout the tool, but I don't think the tool itself should be helping make a decision for the user as to what's best for them (at least not any more than it already does).

Maybe a different tool with a brief questionnaire would be handy, to help users pick the best options for their needs based on their responses.

If you have any particular suggestions I'm happy to hear them, maybe even include some additional text in the tool, but for now I think the level of information available in the tool is appropriate to the intended audience.
