### ISSUE TITLE
Invalid Checksum Warning Not Displayed

### ISSUE THREAD

**Issue by nekrozon** [iancoleman/bip39#158]
First off, love your tool!

Ok so I haven't completely dove into the code yet, but I have noticed that some invalid checksums are allowed with the tool, without a warning/error appearing mentioning the checksum is invalid.

Let's assume a 12 word passphrase. If we divide the 2048 wordlist into groups of 16 ... exactly 1 word out of a 16 word "block" will be shown as a  mnemonic/checksum for the 11 words selected.  Why is this?  How is the checksum being validated?

See this example:

Entropy (128 bits): 11010011 01100100 00000010 01011110 01010011 11101100 01010011 01101110 01101010 01111000 11010010 11011000 10111010 00100011 11101100 11110010

SHA-256 Hash of entropy = 14 c5 8b c9 05 11 5e 08 27 49 61 1e 48 d6 04 c0 2a 70 8c 39 ad 6c dc 0c 91 2f 70 62 c3 24 71 23

First 4 bits of SHA-256 Hash = 1 (hex) Binary = 0001

Generated Recovery Phrase: square cactus nurse pond share rescue prepare bottom suffer speed will tomorrow

another valid phrase (with same entropy but different checksum): square cactus nurse pond share rescue prepare bottom suffer speed will account

Account = 13 (on the BIPS39 wordlist) Subtract 1 since word index starts at 0 = 12 12 to binary = 1100 Hex = C

C (hex) != 1 (hex)

another valid phrase (with same entropy but different checksum): square cactus nurse pond share rescue prepare bottom suffer speed will acoustic

Acoustic = 17 (on the BIPS39 wordlist) Subtract 1 since word index starts at 0 = 16 16 to Binary: 10000 Hex = 10

10 (hex) != 1 (hex)

Thanks Ian!

**Comment by stiVibk** [comment]
You seem to be confused ... a word out of a list of 2048 words means 11 bits (0-2047), so every words represents 11 bits. If you use 12 words you therefor get 132 bits to use, the generator generates a 128bit number, then calculates a 4 bit checksum which determines PART of the 11 bits of the 12th words (last 4 bits).

Same is true for eg. 24 words (24 times 11 = 264, we only use 256bit number so 8 bits of the last word are checksum bits)

**Comment by iancoleman** [comment]
Thanks for this. I'm going to close it in favour of the last task in #132.

See https://github.com/iancoleman/bip39/issues/132#issuecomment-348085868 for more details.

> I would suggest the following tiny additions be made that could help users
> Reveal the resulting checksum in binary format

Thanks @stiVibk for the clarification. Many people seem to be confused about the checksum so having some further clarity in this tool will help all round.

@nekrozon - when the word is changed to `acoustic` in the last example, the first 7 bits of `acoustic` are part of the entropy, the last 4 bits are the checksum. The entropy is different due to these last 7 bits, so the hash (and thus checksum) will also be different.

**Comment by nekrozon** [comment]
Man I’m kicking myself for that mistake!  Thanks @stiVibk and @iancoleman

Is there a mathematical reason, assuming a 12 word phrase, that 1 out of every 16 words is a valid checksum (if you divide the wordlist into blocks of 16, 1 of them will be a valid checksum)?
