### ISSUE TITLE
Can ZCash (ZEC) be added?

### ISSUE THREAD

**Issue by pmgriphone** [iancoleman/bip39#165]
Can you add ZCash (ZEC) to your list of coins so I can generate a ZEC wallet address based on BIP39 seed words.

I know that the root path is BIP44: 44'/133'/0' based on ledger nano wallet info. Not sure if you need to know anything else.

Thx.

**Comment by iancoleman** [comment]
Not at this point in time, see https://github.com/iancoleman/bip39/issues/94 - multibyte pubkeyhash
