### ISSUE TITLE
Extended Public Key different on Ledger nano S

### ISSUE THREAD

**Issue by testosteronecyp** [iancoleman/bip39#168]
@iancoleman 
So I have some bitcoin waiting in escrow and I am trying to get the private key from my ledger nano S from  189YRMzWLwH2CyqMgjVrEWHPcNCizGm6Q multisig.  
My account is segwit: 
3JpnK9hApn85UGnYGcbtiW5dRmqgkLQnB9 
and my exported public keys from: xpub6DLgYmP8gmukUHVnUYR3EwPCFVADatM8u4urwDS6AuewkcPCCFTaxD2HkkZZNwWApE2Q7CQKFcdwfH2hHLM8oEY9EbYbwbdmRJCNTPmFqBq
populate 189YRMzWLwH2CyqMgjVrEWHPcNCizGm6Q as a public key.     I enter the correct mnumonic on bip44 and not only does 189YRMzWLwH2CyqMgjVrEWHPcNCizGm6Q not show up but my extended public key shows:
xpub6DLRqaAnXAgEE6uDpDwYaoATEaMHY2GbcqfpoztTRSJeZLDvyRNocRva47gQzFZfk1DqFER9pNJxSvCiennYUjCgxvJjSnL9XmC4utCXWsi now.   
I can get the segwit private and public addresses to show but for some reason for this multisig transaction I cannot get the keys to show for 189YRMzWLwH2CyqMgjVrEWHPcNCizGm6Q.

It has been over a week now funds are stuck in escrow.  Any help would be greatly appreciated.

**Comment by iancoleman** [comment]
I suggest you seek support from ledger or from a more general platform such as stackoverflow or reddit. If there is a bug or feature for this tool you wish to suggest please let me know, but general support is not provided here.

**Comment by testosteronecyp** [comment]
ya i tried.  they kept giving me generic shit answers.  i wasnt sure if i
was using the program wrong or not.

**Comment by iancoleman** [comment]
Sorry to hear you didn't have any luck on the other support platforms.

Unfortunately I'm in a very busy period so am unable to look into this just now but I'll reopen the issue and come back to it when things quieten down, probably in about two weeks.

**Comment by testosteronecyp** [comment]
getting emailed by people saying they are having the same issue with other currencies.  I wonder what the hell is wrong with the exported public keys but they certainly arent matching.

**Comment by iancoleman** [comment]
Fixed by https://github.com/iancoleman/bip39/commit/f83d786dd7c26e5b3e4feac22f14893464f9f8c4#diff-99a85c3932c0670278158f38d818e0efR2562

* Go to bip32 tab
* Select Coinomi, Ledger client

**Comment by Krinthiran** [comment]
Hi
