### ISSUE TITLE
Deriving ETH addresses from BIP32 Extended Public Key

### ISSUE THREAD

**Issue by dcusan** [iancoleman/bip39#169]
Firstly I wanted to say how helpful your code and page have been for my understanding of BIP's 32, 39 and 44. Thank you!!

I come across an error when attempting the following:

1) Select ETH as a coin in the BIP44 tab and generate a mnemonic and seed
2) Copy the _BIP32 Extended Public Key_ (I leave account and change derivation path members zeroed)
3) Select ETH as a coin in the BIP32 tab and copy the key into the _BIP32 Root Key field_

My expectation would be that with a derivation path of `m/0` the addresses shown below shall match the one listed in tab BIP44. I might be wrong about this as I am rather new to h.d. wallets.

I saw you suggested this in #94. However I see a thrown exception in the console at `keyPair.d.toBuffer`

Hope you can reproduce and help. Thanks again!

**Comment by iancoleman** [comment]
Does the BIP32 Derivation Path `m/44'/60'/0'/0` work (as found on the BIP44 tab)?

Re the console error, which version are you using? This was fixed in v0.3.3 by https://github.com/iancoleman/bip39/issues/155

**Comment by dcusan** [comment]
I've been using the version deployed to [iancoleman.io](https://iancoleman.io/bip39/), just playing with this and trying to learn.

With the derivation path you suggested I'll see the warning `Hardened derivation path is invalid with xpub key`.

This is the exception I see when using `m/0`. I can't use `0` as there seems to be a check in place for the derivation path to start with `m`:

![screenshot](https://user-images.githubusercontent.com/5691039/36736518-20a6614e-1bd9-11e8-923b-f8f3c7a8a088.png)

As a side note I've been able to derive the same addresses from the extended public key shown in BIP44 tab with the `ethereumjs-wallet/hdkey` package.

Anyways, thanks for getting back to me.

**Comment by iancoleman** [comment]
If you put the xpub key here I can look into this but unfortunately just now things are very busy for me so it'll be about 2 weeks until I have time to investigate further.

You may also try path `m` and see if that works but for now this is just generic advice, I'll have a closer look when I get time. Let me know if you find anything else in the meantime.

**Comment by dcusan** [comment]
I've been trying with this extended public key:
```
xpub6DbJyPndTHNa4ykQ1r1kGsASZfvDu5yc4vi43BbKEhVtdcovVQ3ggtCKxnKbkpBhdLnbizdCsWZRJYsbVgXtu9HFkNYFp7ZZX1DdckFRctF
```
It works for BTC, but when selecting ETH a JS error comes up in the console when in the BIP32 tab with both derivation paths `m` and `m/0`.

Sorry for the late reply, hope this helps. Thank you again for this super useful resource!

**Comment by Nathapon8899** [comment]
Thanks for the advice, it has a lot to me ..

**Comment by JeffreyLeonard** [comment]
Im not sure what this means..
