### ISSUE TITLE
About the  algorithms ??

### ISSUE THREAD

**Issue by silence-may** [iancoleman/bip39#176]
Excuse me, 
   What is the difference between the algorithms that generate the address between different currencies?
   I will be looking forward to your reply，thanks!

**Comment by iancoleman** [comment]
There are different parameters for each network that set the encoding of addresses and keys. You can see an example of those parameters in [bitcoinsj-extensions.js](https://github.com/iancoleman/bip39/blob/master/src/js/bitcoinjs-extensions.js).

The underlying mechanism is [ECDSA](https://en.bitcoin.it/wiki/Elliptic_Curve_Digital_Signature_Algorithm).

Note that ethereum and ripple have slightly different mechanisms for their addresses. The code for this is in [index.js L826-841](https://github.com/iancoleman/bip39/blob/fca07769ebffd5a9dffd394643ed3e54704e8a26/src/js/index.js#L826-L841). But again it's all ECDSA underneath.
