### ISSUE TITLE
Are the BIP 32 addresses generated by this tool correct?

### ISSUE THREAD

**Issue by mhluska** [iancoleman/bip39#180]
I'm noticing a mismatch between the addresses generated by this tool and ones generated by some libraries.

Steps to reproduce:

1. Go to https://iancoleman.io/bip39/
2. Enter mnemonic "draft tide jewel life upset reopen genre pink ice select ship rubber risk wrong tree" _(test mnemonic generated for this example)_
3. Click BIP32 tab
4. Notice xpub: xpub69NXF9ahxWHTqqkG6FvUhVP3d8cgBfCsZ4oBnUZTndTUYRTaKPv25AQh5sSdH1kfFKrv6i8brHhxWVZQVZs7yGrbHyoZGoa6de9qYk4gwf5
5. Notice address for m/0/0: `1CXeimhGBpk1Lnbsd5sDZAqgH4A76LQXWd`
6. Now we will try to generate the same address using some bash/Ruby code and the [money-tree](https://github.com/GemHQ/money-tree) gem:

```sh
$ gem install money-tree
$ irb
> require 'money-tree'
> key = 'xpub69NXF9ahxWHTqqkG6FvUhVP3d8cgBfCsZ4oBnUZTndTUYRTaKPv25AQh5sSdH1kfFKrv6i8brHhxWVZQVZs7yGrbHyoZGoa6de9qYk4gwf5'
> master = MoneyTree::Node.from_bip32(key)
> node = master.node_for_path('m/0/0')
> node.to_address
=> 1Ez7bMrVVRDH7VRRwWvAcHZ81mJhcjrcnu
```

We can see this outputs `1Ez7bMrVVRDH7VRRwWvAcHZ81mJhcjrcnu` which is different from the one this tool outputs. If we want the addresses to match up, we need to use no derivation path:

```sh
> node = master.node_for_path('0')
> node.to_address
=> 1CXeimhGBpk1Lnbsd5sDZAqgH4A76LQXWd
```

Which matches the address which this tool outputs.

So I'm not sure if the tool is incorrect or if the gem is incorrect.

**Comment by iancoleman** [comment]
The xpub is not the root pubkey, it's from deeper in the hierarchy (ie the level *after* deriving the bip32 path, which is one step away from each entry in the table).

So the xpub is for derivation path `m/0`, then the addresses are all one step deeper at `m/0/0`, `m/0/1` etc.

So when using that xpub, only one level deeper is needed to generate addresses in the table. This means the xpub is at depth `m/0` and then deriving *one step deeper* to `0` is equivalent to the address at `m/0/0`. This is the 'hierarchy' part of hierarchical deterministic keys.

 To further illustrate, using `m/0/0` in the bip32 tab will generate the address at `m/0/0/0` etc, which is the `1Ez7` address. The example used in the gem has taken the xpub at `m/0` and derived *two steps deeper* using `m/0/0` which ends up giving `m/0/0/0`, ie one level deeper than expected.

Let me know if you think there's anything that could help make this clearer. Derivation paths and depths are probably the most common misunderstanding I hear from in this tool so if it can be clearer it would help reduce my need to respond to similar questions. Thanks for reporting the issue.

**Comment by mhluska** [comment]
This makes sense. Thanks for the explanation. Where in the tool can I find the root pubkey then? It seems to only give the root private key.

**Comment by iancoleman** [comment]
Root xpub is being developed under https://github.com/iancoleman/bip39/issues/152 so I'll see if I can include it in the next release since it would be handy to have.

In the short term you can open the developer tools and this javascript will take the current root xprv and convert it to the xpub:

```
bitcoinjs.bitcoin.HDNode.fromBase58($(".root-key").val()).neutered().toBase58()
```
