### ISSUE TITLE
Offline generation

### ISSUE THREAD

**Issue by okduxvcg** [iancoleman/bip39#184]
Is there any .jar browser (for an old phone using java (MIDP 2.1) that I could install to generate offline passphrase?

**Comment by iancoleman** [comment]
I don't know of any browser specifically but it should work in most browsers. The main limitation is likely to be whether `crypto.getRandomValues` is present in an old browser, but you can always supply your own entropy if it's not available. Other than that the tool has polyfills for NFKD etc so I should expect it to work on almost all browsers.

If you do test / find one I'd be interested to hear your results.

**Comment by okduxvcg** [comment]
Yes, I tried internat browser on an old samsung phone - it opened the website but cannot generate seed. There's also opera mini browser (still developed?) but on their page they write it's unable to run offline files (wonder why in settings there's tab for local files).

Maybe other users tried any jar file? 

Still if we talk about offline generation - do you think that it would be safer to use dedicated laptop or old phone? My samsung do not have wifi, I turn on airplane mode - any chance to have some leak when there is no sim inserted as well?

**Comment by okduxvcg** [comment]
So any experiences with offline laptop/phone? Which is safer? In terms of being handy phone is easier to use/destroy/move.

**Comment by iancoleman** [comment]
I think simpler io on a laptop makes it a better candidate (not necessarily safer or more dangerous though). But this is probably a discussion better had with the broader bitcoin community than the small number of people viewing this issue.

**Comment by iancoleman** [comment]
Not really an issue with the tool, more with how it's used, and has no feature that can be implemented to resolve, so I'm closing the issue.
