### ISSUE TITLE
How to derive PublicKey from BIP32 Extended Public Key?

### ISSUE THREAD

**Issue by aKaigege** [iancoleman/bip39#185]
Do you have any demo ?

**Comment by iancoleman** [comment]
* Paste the xpub key into the field labelled 'BIP32 Root Key'
* Select BIP32 tab
* Enter the correct derivation path (depends on your particular use case and where in the hierarchy the xpub comes from)
* See the table is populated with public keys and addresses etc.

If you have any further questions or clarifications I'm happy to go into more details.
