### ISSUE TITLE
Supporting Coins that don't use SHA256D for Addresses

### ISSUE THREAD

**Issue by HashEngineering** [iancoleman/bip39#191]
We would like to add support for GRS to your repo.

GRS (Groestlcoin) is unique because it does not use SHA256D for the checksum on extended keys and addresses, but instead it uses double groestl (sha3 candidate).

We are wondering what the best way is to make code changes to submit as a pull request.

In the past, I had modified bitcoinjs to use the correct hash function based on added parameters added to some of the functions.  This solution makes it hard to upgrade bitcoinjs after changes are made.

Another option may be to include a groestlcoinjs library.  My concern with this is that there may be name conflicts with bitcoinjs, as they use the same names for functions.  Perhaps JavaScript has a way around this, but not sure.

Would there be a better way to handle adding coins, such as Groestlcoin, that use different hash functions?

**Comment by iancoleman** [comment]
> We are wondering what the best way is to make code changes to submit as a pull request.
> ...
> Would there be a better way to handle adding coins, such as Groestlcoin, that use different hash functions?

The main place this is affected is the table of addresses / keys. Have a look at [how ethereum and ripple do it](https://github.com/iancoleman/bip39/blob/db37d63919f1812dd5904b043e5b727bb1591500/src/js/index.js#L826-L841).

There is just a conditional that calculates the correct address / pubkey / privkey depending on the specific coin, and a library included for those operations, eg [ethereumjs-util.js](https://github.com/iancoleman/bip39/blob/db37d63919f1812dd5904b043e5b727bb1591500/src/js/ethereumjs-util.js) and [ripple-util.js](https://github.com/iancoleman/bip39/blob/db37d63919f1812dd5904b043e5b727bb1591500/src/js/ripple-util.js)

Modifications to bitcoinjs-lib will not be accepted as a pull request.

Also see https://github.com/iancoleman/bip39/issues/94 - Multibyte pubKeyHash - zcash.

**Comment by iancoleman** [comment]
I will leave this issue to the groestlcoin community to submit a pull request containing the feature.

**Comment by gruve-p** [comment]
#https://github.com/Coinomi/bip39/pull/6
