### ISSUE TITLE
Something new that could speed up the word checking

### ISSUE THREAD

**Issue by DeepQuasar** [iancoleman/bip39#195]
If one has newly created a 24 recovery phase and one word is at least wrong. To be able to speed up the process a little more would it be possible to create a script from words in this link below.
https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

In essence if one entered all the 24 words into the bip39 offline master could one then somehow use a script to copy and paste one word at a time into the offline master to check that the word 18 for example is correct. Maybe it might be possible to create a log for all the words that have been tried for the number word.

**Comment by iancoleman** [comment]
What process is being sped up?

**Comment by DeepQuasar** [comment]
Nothing is being sped up I mean is it possible to implement a way to speed up the word checking for 1 missing word from a 24 word seed. Like a way to go through these words faster by implementing a log so it will find the missing word.  https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

**Comment by iancoleman** [comment]
There are many possible words that could be valid for the missing word. To find the 'correct' missing word requires looking up the blockchain to see if the keys have transactions. This is a very complex addition and not suitable for this tool. I'd describe this as a mnemonic recovery tool, and is outside the scope of this tool.

It's not a bad idea per se, just not suitable for inclusion in this tool.

Maybe this is useful: https://github.com/ashmoran/bip39_missing_word
