### ISSUE TITLE
standalone does not generate keys?

### ISSUE THREAD

**Issue by roryfrost** [iancoleman/bip39#203]
Can anyone help me...my stand alone version doesn't calculate the keys. I downloaded the website and transferred it with USB to my stand alone laptop. But if I enter the mnemonic code and select the coin, nothing happens. I followed the instructions as on this website: http://damien.la/2017/09/10/mnemonic. The online tool works fine though. Could it be that my windows version (Windows 7) on the stand alone laptop is too old? Many thanks for your help!

**Comment by iancoleman** [comment]
Do you see an error message?

If you open the developer tools is there anything in the console?

What browser are you using?

**Comment by iancoleman** [comment]
Long time to respond, no longer an issue? Closing this issue unless further feedback is available.
