### ISSUE TITLE
Support different derivation path for Ethereum family coins

### ISSUE THREAD

**Issue by xarakas** [iancoleman/bip39#204]
Hi, 
the current version generates change addresses (e.g. m/44'/60'/0'/0/0),
however wallets like Coinomi and Ledger use account addresses (e.g. m/44'/60'/0'/0).

Could you indicate a way of incorporating a menu where the user could select which of the two ways to utilize?

One possible solution is to add a dropdown menu for such coins (e.g. ETH, ETC, MIX, PIRL, etc.) and force the user to select which one to use.

Thank you in advance!

**Comment by iancoleman** [comment]
This is already supported via the bip32 tab using a custom derivation path.

The BIP44 tab in this tool explicitly follows the bip44 specification. Coinomi and ledger do not follow the bip44 specification.

There's reasonable arguments for why these coins don't follow the bip44 spec (see https://github.com/ethereum/EIPs/issues/84, "`change` doesn't make much sense for an account-based architecture like Ethereum") but if it's not following the standard it's not bip44, simple as that.

**Comment by erasmospunk** [comment]
@iancoleman BIP44 defines only coin type indexes, not how each coin uses the account private key.

If you take Monero as an example, it is by definition incompatible with the proposed standard of BIP32 (different curve, the priv/pub is created with the transaction data, has spend & view private keys).

In case of Ethereum, many users are using the alternative paths and will be confused when missing their addresses.
