### ISSUE TITLE
Support Zcash family coins

### ISSUE THREAD

**Issue by xarakas** [iancoleman/bip39#205]
It seems that the current version of bitcoinjs does not allow public key and private key headers with four hexadecimal digits, which is the case for zcash and its clones (BTCP, BTCZ, ZCL, ZEN, etc.).

Would you accept changes in the source code that would support such cases?

**Comment by iancoleman** [comment]
Please see https://github.com/iancoleman/bip39/issues/94

> I'm not willing to fork / modify bitcoinjs-lib to support this feature. I've subscribed to the relevant issue in bitcoinjs-lib, so when this feature is ready I'll look into addressing this issue.

If this feature can be implemented without forking bitcoinjs-lib, ie with some sort of zcash-lib I would consider adding it (as has been done for ethereum and ripple).

**Comment by xarakas** [comment]
I created PR (#212) that illustrates the minor changes required in bitcoinjs to also support zcash.

**Comment by iancoleman** [comment]
Closed via https://github.com/iancoleman/bip39/pull/212
