### ISSUE TITLE
XLM withdrawl problem

### ISSUE THREAD

**Issue by P1968** [iancoleman/bip39#220]
Tried to transfer XLM to another account.  When transferring, did NOT include a "MEMO" as the example said it was optional.  Asset was sent successfully and address was correct, however, XLM was never received on the other end....been 4 hours.  Tried it 2x unsuccessfully.  Tried it a third time with a MEMO and it was received a few seconds later.  Any ideas?

**Comment by iancoleman** [comment]
This is not a support forum. Please ask elsewhere unless there is an issue specific to this tool.
