### ISSUE TITLE
Derivation path for Litecoin testnet

### ISSUE THREAD

**Issue by Josema** [iancoleman/bip39#221]
Hi, sorry for asking this here but I couldn't find anywhere. Does anybody know what is the derivation path for Litecoin Testnet?

**Comment by iancoleman** [comment]
Best to ask litecoin reddit or bitcoin stackexchange, but the derivation path depends on the particular derivation scheme you're using. [SLIP0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) says all testnet coin indexes should be 1 (ie bip44 litecoin testnet with account X change Y is `m/44'/1'/X'/Y`), but that's only if you're using BIP44 or something based on that derivation scheme (eg BIP49 or 84).
