### ISSUE TITLE
get rid of in-tree standalone

### ISSUE THREAD

**Issue by jsarenik** [iancoleman/bip39#226]
This is a suggestion in order to ease future development and get rid of bloated git history containing the compiled result.

Please have a look at https://github.com/jsarenik/bip39/commit/5215311ccdc0fe5b161dc82df1c46664f736a075

```
lomidrevo:~/Downloads$ ls -lh bip39-*
-rw-r--r-- 1 jasan jasan 1.2M Jul  9 12:36 bip39-jasan-rewritten.zip
-rw-r--r-- 1 jasan jasan 2.4M Jul  9 12:36 bip39-master.zip
```

It might not be so bad yet, but I have seen repositories with hundreds of GBs of generated blob.

For reference: https://github.com/samhocevar/wincompose/issues/16

`bip39` is a wonderful piece of software. Thank you!

**Comment by iancoleman** [comment]
Good suggestion. Now that releases are being made it's a good idea to remove it from the repo. Thanks for the suggestion.

**Comment by jsarenik** [comment]
You are welcome. Good job. Respect.
