### ISSUE TITLE
XMR support - please add

### ISSUE THREAD

**Issue by gitmanfa** [iancoleman/bip39#227]
Dear ,
               please add the xmr support in your tool . Thanks

**Comment by iancoleman** [comment]
The xmr community is welcome to make a pull request if they would like it included in the tool.

**Comment by powerkangaroo** [comment]
[Coinomi's fork](https://github.com/Coinomi/bip39-coinomi) of this repo added a way to derive a Monero seed from a BIP39 seed, and thus also addresses.

@PavlosTze is it possible to pull the Monero modification into this repo?
