### ISSUE TITLE
Bitcore (BTX) changed address prefixes in 0.15.1.0.

### ISSUE THREAD

**Issue by dan-da** [iancoleman/bip39#231]
PUBKEY_ADDRESS:   0 --> 5
SCRIPT_ADDRESS: 0 --> 125

See https://github.com/LIMXTEC/BitCore/commit/0ee70eb84f6b36ca2c69036e62c6c0f67312aa7a

old p2pkh address: 1LduV2rRQAcTW1BbaDxjR7r2UwnYdsWSUM
new p2pkh address: 2YeiSMkHXi15xJbreUxgsVfPNTZNmZRHHS

**Comment by iancoleman** [comment]
Thanks for this.

PUBKEY_ADDRESS is 3 not 5.

See https://github.com/LIMXTEC/BitCore/commit/0ee70eb84f6b36ca2c69036e62c6c0f67312aa7a#diff-64cbe1ad5465e13bc59ee8bb6f3de2e7R148

I'll include this change in the next release.
