### ISSUE TITLE
Wordlist relief

### ISSUE THREAD

**Issue by opensourcesawmill** [iancoleman/bip39#247]
The word relief is in the wordlist, but if you use it in the tool it you get the error 'invalid mnemonic'.

**Comment by iancoleman** [comment]
`ability famous relief` doesn't show an error for me, please provide more info.

**Comment by opensourcesawmill** [comment]
I go to the following url: https://iancoleman.io/bip39/ - change the selection to 24 words - click generate - paste over any word with relief - i get the error invalid mnemonic - it does this in both chrome and brave.

But, if I do the same thing with a 3 word mnemonic, it works fine.

**Comment by iancoleman** [comment]
You can't just replace a word randomly because the last words are a checksum and this replacement will usually cause that checksum to become invalid.

I should update the error to say 'invalid checksum'. The general error is not particularly helpful there!

Thanks for reporting.

Here's a snippet to paste into the browser dev tools that will generate a valid 24 word mnemonic containing the word relief:

```
M = new Mnemonic("english"); for (i =0; i<500; i++) { m = M.generate(256); if (m.indexOf("relief") > -1) { console.log(m); break }}
```

example output

```
knock salon picnic fever online essay scissors rookie cube surprise exchange buyer ripple little common hotel blast material bright payment relief two ranch barely
```

**Comment by opensourcesawmill** [comment]
I sort of figured it out finally. I wanted to add my own bit of tweaks, so
id click generate several times and combine words from various
combinations. I ended up moving all 24 words to notepad and then copied
them in all at once.

Sorry, but thanks

On Aug 30, 2018 4:12 PM, "iancoleman" <notifications@github.com> wrote:

You can't just replace a word randomly because the last words are a
checksum and this replacement will usually cause that checksum to become
invalid.

I should update the error to say 'invalid checksum'. The general error is
not particularly helpful there!

Thanks for reporting.

Here's a snippet to paste into the browser dev tools that will generate a
valid 24 word mnemonic containing the word relief:

M = new Mnemonic("english"); for (i =0; i<500; i++) { m =
M.generate(256); if (m.indexOf("relief") > -1) { console.log(m); break
}}

example output

knock salon picnic fever online essay scissors rookie cube surprise
exchange buyer ripple little common hotel blast material bright
payment relief two ranch barely

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/iancoleman/bip39/issues/247#issuecomment-417497105>,
or mute
the thread
