### ISSUE TITLE
how to convert entire project in node js 

### ISSUE THREAD

**Issue by manoj-djax** [iancoleman/bip39#248]
I want to generate series of address for all types of cyptocurrencies listed in this project, in node js, can you please guide us for this

**Comment by iancoleman** [comment]
I won't write a guide but have a look at these libraries:

https://github.com/bitcoinjs/bip39
https://github.com/bitcoinjs/bitcoinjs-lib
https://github.com/bitcoinjs/bip44-constants
https://github.com/bitcoinjs/bip32
https://github.com/bitcoinjs/bech32
https://github.com/bitcoinjs/bip32-utils

and this file containing network parameters for all the extra networks

https://github.com/iancoleman/bip39/blob/master/src/js/bitcoinjs-extensions.js
