### ISSUE TITLE
Request - XLM Address cross reference option in addition 

### ISSUE THREAD

**Issue by sp3sh** [iancoleman/bip39#262]
Hello, Sorry if I don't have all the technical jargon but a friend of mine has mucked up his ledger 24-word phrase somehow and the only transacted address is XLM - is there a way to cross check the XLM address as you do with BTC?

Unfortunately, he never used any other currency on the device so we have no real starting point just 24 words written down that should be mostly correct. If this would be easy to do or instructions for me to do so I would appreciate it immensely and would be able to provide a reward if he can recover his XLM

**Comment by iancoleman** [comment]
Maybe ask the xlm community? I doesn't look like this tool currently supports that currency. It probably could, but would need network parameters for that coin to be added to this tool.
