### ISSUE TITLE
Please add Tezos

### ISSUE THREAD

**Issue by dawsy8888** [iancoleman/bip39#275]

**Comment by iancoleman** [comment]
Please ask the Tezos community to submit a pull request to add their coin to this tool.

**Comment by tndnz** [comment]
Hello,
Isn't what you can find there enough to register tezos?:
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by Xelendor1** [comment]
Can we please open this and I will reach out the community and find some way to get us added.

**Comment by wigy-opensource-developer** [comment]
Just send a pull request with the code changes (parameters, UI tests, etc.), similar to other coins, and that will be reviewed and merged by Ian.
