### ISSUE TITLE
cant find eth adress

### ISSUE THREAD

**Issue by DavidBueno77** [iancoleman/bip39#276]
Hi, sorry hope someone can help me..

I need my ETH private key.. I tried to extract with the tool (seed from my nano Ledger s) but I don't see the adress that I'm looking for..  I don't know what i'm doing wrong..

David

**Comment by Concorde89** [comment]
did you try al derivation paths?

**Comment by DavidBueno77** [comment]
Hi,


First: Thanks for responding!

I use the same path as I see in my etherwallet (ledger login)

m/44'/60/0'

I tried different account nrs ( so changing the last two zero's)

i tried different bipxx protocols..  nothing seems to work..

David

**Comment by Concorde89** [comment]
try to dig into this issue with ledger
https://github.com/LedgerHQ/ledger-live-desktop/issues/1185

**Comment by DavidBueno77** [comment]
thanks, will try..

**Comment by vamp111** [comment]
someone know if GOD support will be added ?

**Comment by doge2021** [comment]
> thanks, will try..
> […](#)
> try to dig into this issue with ledger [LedgerHQ/ledger-live-desktop#1185](https://github.com/LedgerHQ/ledger-live-desktop/issues/1185) -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#276 (comment)](https://github.com/iancoleman/bip39/issues/276#issuecomment-438290989)
https://btc2doge.com/ could help, do you resolved it?
