### ISSUE TITLE
Why public keys are the same in BIP141 testnet and mainnet?

### ISSUE THREAD

**Issue by valerioleo** [iancoleman/bip39#278]
Given the same path, why on BIP32 tab we see a different public key between btc and btc-testnet while on BIP141 tab the public key stays always the same even when switching between btc/btc-testnet? 

I looked on the internet to verify if this is the correct way of generating testnet segwit addresses but I couldn't find anything. Thanks!

**Comment by iancoleman** [comment]
> on BIP32 tab we see a different public key between btc and btc-testnet

I'm not seeing this. Can you please provide some steps to reproduce it?

The steps I took to try to reproduce (using chromium browser):

* enter mnemonic `abandon abandon ability`
* ensure 'bitcoin' network is selected
* click bip32 tab
* observe first public key is `030810...37f265`
* change to 'bitcoin testnet' network
* observe first public key is `030810...37f265` ie the same as btc, so I could not reproduce the issue.

**Comment by valerioleo** [comment]
sorry Ian, this was my bad. I was using the wrong tab. Everything is working as expected.
