### ISSUE TITLE
Add a disclaimer

### ISSUE THREAD

**Issue by dangershony** [iancoleman/bip39#28]
Hi, perhaps you may want to add a disclaimer to the web tool, something like "use it at your own risk"

**Comment by iancoleman** [comment]
Good idea.

I added the MIT license just now, but I think a disclaimer in the webpage itself is useful.

https://github.com/iancoleman/bip39/blob/master/LICENSE

**Comment by iancoleman** [comment]
The page itself contains a link to the license and the specific content of the license that concerns liability.

https://github.com/iancoleman/bip39/commit/1f618a7792e4b29bd06481239001e57a1aa58a37 - License details in More Info section
