### ISSUE TITLE
Bitcoin GOD 

### ISSUE THREAD

**Issue by vamp111** [iancoleman/bip39#288]
hi, anyone aware if support for Bitcoin GOD (not GOLD) can be added and if its easy to be done, seems that the main Core God wallet is out of sync im having trouble restoring my tokens with the wallet.dat file, it displays only the transactions, but shows only 0 amount.

**Comment by Antoxa223** [comment]
Send the address

**Comment by vamp111** [comment]
the adress of what?

**Comment by iancoleman** [comment]
Please ask the GOD community to submit a pull request to add their coin to this tool.
