### ISSUE TITLE
Aion Integration?

### ISSUE THREAD

**Issue by a-toad-a-so** [iancoleman/bip39#290]
Request to add Aion to the tool. 
Novice coder here, but some of this code might be helpful(?)

https://github.com/aionnetwork/aion_ledger/blob/5ab1e434257ee54d028ada0c9ff298213abe480b/src/main.c
https://github.com/aionnetwork/aion_ledger/blob/5ab1e434257ee54d028ada0c9ff298213abe480b/test/test_cases.py
https://github.com/aionnetwork/aion/blob/ebbb7a982228bac0fc0590cd2bc7ecf8fa221046/modGui/src/org/aion/wallet/util/CryptoUtils.java

**Comment by iancoleman** [comment]
Please ask the Aion community to submit a pull request adding this coin to the tool.
