### ISSUE TITLE
Python Integration

### ISSUE THREAD

**Issue by Swaggadan** [iancoleman/bip39#292]
Is there anyway I can integrate some of these commands and outputs into python? Would love a way to have it generate Eth or BTC addresses within python code.

**Comment by iancoleman** [comment]
I'm sure there are python libraries for BIP39 / BIP32 / BIP44 / BIP49 / BIP84 etc but am not familiar with the current state of that particular ecosystem myself.

The main challenge will probably be creating a useful UI.

For now this isn't something I'm going to pursue, although I do think a local command-line version of this tool would be great (I'd probably write it in go for the simplest cross-platform distribution).

**Comment by hatgit** [comment]
In case it helps, here is one I built from scratch and recently improved but it only generates entropy (in addition to manually pasted entropy) and the resulting bip-39 compliant mnemonic (which could then be pasted in to the BIP39 tool in this repo for address/wallet creation and access): https://github.com/hatgit/BIP39_mnemonic_creation_light_python/blob/master/bip39appv1_8.py

**Comment by Swaggadan** [comment]
Thank you sir
