### ISSUE TITLE
Website not up-to-date with Github

### ISSUE THREAD

**Issue by TronBlack** [iancoleman/bip39#294]
https://iancoleman.io/bip39 code does not match master on https://github.com/iancoleman/bip39

RVN - Ravencoin is available on the master branch, but not available on the website.

**Comment by iancoleman** [comment]
I try to wait for several changes before creating a new release. I've been bogged down over the last month but plan early in Feb to close a bunch of issues and make a new release. So this should be on the live site hopefully early Feb. Thanks for the reminder!

**Comment by iancoleman** [comment]
Just updated to 0.3.10 on iancoleman.io/bip39/ with RVN included.
