### ISSUE TITLE
how to generate a Zpub/Zprv (P2WSH) ?

### ISSUE THREAD

**Issue by farzher** [iancoleman/bip39#301]
trying to create a multisig segwit wallet using electrum.
idk what i'm doing but i pasted in every possible key you could generate, none worked. i think i need a Zprv (capital Z).

i'm just trying to make an electrum multisig segwit wallet using my own entropy (i wish i could just import a standard BIP39 Mnemonic but electrum uses a custom word list).

**Comment by iancoleman** [comment]
electrum can import bip39

* start electrum
* new wallet
* Standard wallet
* I already have a seed
* Options button
* BIP39 checkbox
* Continue with the remaining prompts as per your needs.

This is not a place for support so any further questions please ask in electrum repository or on stackexchange/bitcointalk/reddit thanks.

**Comment by farzher** [comment]
thanks for the tip, but i have to use electrum mobile, which doesn't have this option.

sorry for asking a support question, but do you know why this tool can generate seemingly everything except a Zprv? i could ask elsewhere how to generate a Zprv but i like this open source tool and would like to use it if possible. i thought i was just missing some option and this question would be a useful landing page for anyone with a similar issue.

if you guys actually don't support Zprv because you don't think it's important enough or something, do you recommend i just go with a non-segwit wallet?

**Comment by iancoleman** [comment]
Zpub (capital z) is unique to electrum mnemonics (specifically their segwit multisig) and not used by bip39 or any other bitcoin wallet (to my knowledge).

Electrum mnemonics are not bip39 mnemonics. They do things their own way.

**Comment by farzher** [comment]
i see... didn't realize that was electrum specific. had trouble finding any info about this on google.
thank you!
