### ISSUE TITLE
Please add Swap (XWP)

### ISSUE THREAD

**Issue by RainbowMiner** [iancoleman/bip39#303]
Since the Swap project gears up fast and strong, I would be more than happy, if you could add Swap (https://swap.fyi) to your bip39 generator. There is a running ledger app avail, already at https://github.com/swap-dev/ledger-app-swap/releases

Thank you so much, in advance!

**Comment by iancoleman** [comment]
Please ask the Swap community to submit a pull request to add the coin to this project.
