### ISSUE TITLE
Add multiple languages for the wordlists

### ISSUE THREAD

**Issue by iancoleman** [iancoleman/bip39#31]
See https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

**Comment by HostFat** [comment]
This would be really appreciated :)

**Comment by iancoleman** [comment]
The first step has been completed - adding wordlists to the underlying mnemonic library

https://github.com/iancoleman/jsbip39/commits/master

https://github.com/iancoleman/jsbip39/commit/dc9088001fd76a323c62e216cb47c2629c5650d6 through to https://github.com/iancoleman/jsbip39/commit/03202b6f96bdf7c57e3c13c5fb9eb71da9db882a

**Comment by iancoleman** [comment]
Implemented and live.

https://github.com/iancoleman/bip39/commits/master

https://github.com/iancoleman/bip39/commit/7c31e3cd23202ae93fb4736ae96b4acae6dafacb through to https://github.com/iancoleman/bip39/commit/92b46ab44fb7fe7aef1cef3d843d1e3d19c1d7cb
