### ISSUE TITLE
Improvement (?) proposal: show binary entropy  corresponding to BIP39 Mnemonic 

### ISSUE THREAD

**Issue by baro77** [iancoleman/bip39#318]
Hi actually you have 2 way to enter main entropy: 

1) directly digiting BIP39 mnemonic

2) digiting you own entropy ticking "Show entropy details" panel

However when you choose the second way, the "BIP39 mnemonic" field becomes an output one, deleting any words you have previously written, if any.

Wouldn't it be a nice feature to sync "BIP39 mnemonic" and "Entropy" fields?!.. I mean: when you begin to fill "Entropy" the "BIP39 mnemonic" is dinamically filled accordingly (as it already acts), but what about being able to modify the "BIP39 mnemonic" as well, causing "Entropy" update? (I mean the input and output roles of the two field should be decided by which of the two fields was typed.. btw, i guess the "Entropy" field should be populated by binaries when acting as output )

Thanks!
Andrea

**Comment by iancoleman** [comment]
Why is this a nice feature? I don't understand what benefit this gives to users. I'm open to being convinced but it seems like not a useful feature to me.

**Comment by baro77** [comment]
Hi! Sorry for the many Easter days off. I was thinking to the following scenario:
I generate my own entropy tossing a coin and I keep it stored offline for maximum security: I use BIP39 Tool on a strictly offline computer to generare extendend public key for my daily watch-only wallet and private keys when I need any of them; stated it's easier to store on a paper the BIP39 Mnemonic than the binary entropy (and trash the latter), I think it would be convenient to use BIP39 Tool to obtain back the binaries, if needed (of course I image there are other suitable tools out there, but I think it would be more convenient to minimize the number of tools/software you need to rely on for "secret supply chain")

**Comment by iancoleman** [comment]
> generate my own entropy ... keep it stored offline for maximum security

This is not best practice. It's best practice to store mnemonics, not entropy.

> obtain back the binaries, if needed

Why would binary entropy be needed again?

I'm not against the feature per se, it's fine to decode and display the entropy from the mnemonic. But I consider this to be work for no purpose and all the justifications for it come from doing poor practices.

If it were a pull request I'd probably accept it but I don't plan to implement this feature based on the existing justifications.

**Comment by baro77** [comment]
I got your points! Anyway thanks for the time you have spent dealing with my idea! When I'll have the right time and skills, I'll try to submit that pull-req ;) Bye for now! :)

**Comment by baro77** [comment]
Hey Ian! thanks to have implemented it in v0.3.13!
