### ISSUE TITLE
show public key per address

### ISSUE THREAD

**Issue by dooglus** [iancoleman/bip39#32]
I use Bitcoin Core's "watch only" addresses to track my BIP44 wallet. I would like to be able to use "createrawtransaction" and "fundrawtransaction" to have it create a raw transaction which I could then sign using my offline machine, but "fundrawtransaction" only works for addresses that I have imported using "importpubkey" rather than using "importaddress".

That is, Core needs to know the public key of the addresses it is watching in order to create a raw transaction that spends them. And that information isn't currently available to me from this website.

I would like to see a new column, after "Path", "Address", and "Private Key" called "Public Key", which I could use with Bitcoin Core's "importpubkey" RPC call. Or maybe it could be a toggle, alternating between "Private Key" and "Public Key". Maybe default to only showing the Public Key even.

**Comment by iancoleman** [comment]
Great idea.

See https://github.com/iancoleman/bip39/commit/1b12b2f5f12b32a2ed6e69ff77f10b889b383e97

I think showing both public and private key is most intuitive. I prefer not to hide information behind ui state if avoidable. It makes the table wider but that's fine.

**Comment by dooglus** [comment]
Nice. I thought I may have already brought this up to you, but I guess not.

Did you consider using a fixed-width font for the table? The public keys are all the same length, but you'd never know it looking at the jagged columns it produces.
