### ISSUE TITLE
Has the strandalone version been removed from the repo?

### ISSUE THREAD

**Issue by thinkloop** [iancoleman/bip39#325]
> Standalone offline version - Download bip39-standalone.html

Has the strandalone version been removed from the repo?

**Comment by iancoleman** [comment]
Yes it's removed from the repository and now available in the releases.

See https://github.com/iancoleman/bip39/issues/226

I'll update the readme, thanks for pointing this out.

**Comment by iancoleman** [comment]
Also see https://github.com/iancoleman/bip39/commit/dfa696859af863cb46618bc59db62fbe0a6302a4 for the fix.

**Comment by thinkloop** [comment]
Thanks! You really are the best.
