### ISSUE TITLE
Is auto-spellcheck feature disabled by default?

### ISSUE THREAD

**Issue by andronoob** [iancoleman/bip39#329]
Recently, Coinomi was accused for enabling spellcheck feature by mistake: https://www.reddit.com/r/CryptoCurrency/comments/av7gfi/warning_coinomi_wallet_critical_vulnerability/

I wonder is this a security hole? If so, should we fix it?

**Comment by iancoleman** [comment]
Thanks for reporting this, I really appreciate it.

I'm going to add tags to disable spellcheck as per https://stackoverflow.com/a/254716

Whether this is actually a security hole... I found no indication that spellcheck is ever done via remote services in the browser. Any more info on this would be welcome.

**Comment by iancoleman** [comment]
See https://github.com/iancoleman/bip39/commit/bea736aeae48b4c17494bed15a987b05206b1486 for fix

**Comment by andronoob** [comment]
Please fix the typo:
```
Forec spellcheck and autocomplete to be off
```
