### ISSUE TITLE
xpub, xprv level 3

### ISSUE THREAD

**Issue by bom64** [iancoleman/bip39#34]
Mycelium only import level 3, not level 0 or 4 generated in this project. Any plan to support level 3 xpub/xprv? The point is to generate a receive only HD account until it is time to import the xprv.

**Comment by iancoleman** [comment]
I'm not clear what is meant by 'level 3'.

In the BIP32 tab Mycelium wallet derivation path is listed as `Use path m/44'/0'/0'/0` (ie BIP44)

Is your suggestion for this be changed?

**Comment by bom64** [comment]
I don't think path m/44'/0'/0'/0 shout be change - but I don't know.
If Reinstall Mycelium and Open Mycelium, select "Create New" (not restore) wallet and then go to Account and select Export so xpub or xprv is displayet and then eg on another device running Mycelium "ADD ACCOUNT", navigate to Advance and then scan xpub or xprv from the other device the import of xpub or xprv is working. 

But import of xpub or xprv from you tool give error:
Not support level 0 or level 4.

Hope it help.

**Comment by iancoleman** [comment]
I exported my key and found that the following derivation path matches the xpub key:

`m/44'/0'/0'`

I'll add a bit of extra text to the Mycelium Wallet explaining which path to use.

Thanks for pointing this out.

**Comment by iancoleman** [comment]
The Mycelium Wallet derivation path has better text with the changes in https://github.com/iancoleman/bip39/commit/535c9d0f4aec39cc2515ed08c8ca1ca51d80c303.

Click the BIP32 tab in the UI to see these changes.

```
m/44'/0'/0' generates extended keys for import / export.
m/44'/0'/1' to generate the next account. Continue incrementing for more accounts (most use a single account).
m/44'/0'/0'/0 to generate public addresses.
m/44'/0'/0'/1 to generate change addresses.
For more info see the Mycelium Wallet homepage
```
