### ISSUE TITLE
SLIP-39 Shamir Backup support?

### ISSUE THREAD

**Issue by jonathancross** [iancoleman/bip39#354]
Trezor now ships with support for [SLIP-0039 : Shamir's Secret-Sharing for Mnemonic Codes](https://github.com/satoshilabs/slips/blob/master/slip-0039.md).

Although it seems [a bit less efficient than your implementation](https://github.com/trezor/python-shamir-mnemonic/issues/15#issuecomment-525314995), it would nevertheless be fantastic if you could add support for this emerging standard in your BIP39 tool.  This would greatly benefit users by giving them an easy way to restore SLIP39 wallet even if they don't have a hardware device supporting the standard.

Might be helpful:

* https://github.com/ilap/slip39-js

Related: #73 , https://github.com/iancoleman/shamir39/issues/10

**Comment by iancoleman** [comment]
Yeah I'm keen to make a similar tool for SLIP39, but it would be a standalone tool rather than integrated with this one. Thanks for the link to slip39-js, that'll be handy in the future.

**Comment by jonathancross** [comment]
I just discovered https://iancoleman.io/slip39/ -- Nice!
