### ISSUE TITLE
"Use hardened addresses" affects all tabs, so should be moved up

### ISSUE THREAD

**Issue by dooglus** [iancoleman/bip39#366]
The BIP32 tab has a "Use hardened addresses" checkbox. It affects the addresses that are generated on all 5 tabs, and so shouldn't be hidden away on the BIP32 tab, but would be better positioned above the tabs so it is always visible.

Having it on the BIP32 tab lead me to think that I couldn't use hardened addresses on any of the other tabs.

**Comment by iancoleman** [comment]
Thanks, good catch.

See https://github.com/iancoleman/bip39/commit/9ce31d35094acc66eb0faf2d25eeac3a57438bc2 - Move hardened addresses checkbox to address table
