### ISSUE TITLE
add Bitcoin -regtest compatibility?

### ISSUE THREAD

**Issue by dooglus** [iancoleman/bip39#379]
I'm trying to generate bech32 addresses for Bitcoin's regtest mode, but am not seeing it in the list of available networks.

I think for the purposes of this site `-regtest` is the same as `-testnet`, but with a bech32 prefix of `bcrt` instead of `tb`.

To test this I tried replacing the 3 occurrances of `'tb'` in `bip39-standalone.html` with `'bcrt'` and that did allow me to create the bech32 addresses that I needed.

**Comment by iancoleman** [comment]
Thanks for this.

See https://github.com/iancoleman/bip39/commit/f12242014d1ed5c7606c3350a9780c3883abc565 - Add bitcoin regtest params
