### ISSUE TITLE
BIP39 Mnemonic

### ISSUE THREAD

**Issue by ARTEMKA-STOM** [iancoleman/bip39#383]
why at input of the phrase bip39 Mnemonic on the index conceived by me;(355 26 476 43 745 374 1 686 34 132 602 45
clump add derivative aim fringe concert abandon fiber aerobic away enroll airport)- iancoleman.io/bip39 / changes the index of words to 1 digit of the table(https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt#L40) I need precisely on this index introduce words but site changes significance index
![ян1](https://user-images.githubusercontent.com/19418865/69834115-40b23980-125a-11ea-8dc5-cfb61136daff.PNG)
![ян2](https://user-images.githubusercontent.com/19418865/69834116-414ad000-125a-11ea-8e6b-e8df364243a7.PNG)
![ян3](https://user-images.githubusercontent.com/19418865/69834117-414ad000-125a-11ea-9eda-cc75e2c973aa.PNG)

**Comment by iancoleman** [comment]
The wordlist indexes are between 0 to 2047 (in binary 00000000000 to 11111111111)

The list on github is displayed with line numbers, ie 1 to 2048. Note that 2048 is 12 bits long, ie 100000000000 whereas bip39 uses only up to 11 bits.

This is standard zero based numbering.
