### ISSUE TITLE
Pasting BIP39 seed does not restore mnemonics

### ISSUE THREAD

**Issue by kirillkovalenko** [iancoleman/bip39#394]
Current behavior:

If I insert BIP39 seed into the corresponding area the BIP39 mnemonic area remains empty.

Expected behavior:

When I insert BIP39 seed into the corresponding area the BIP39 mnemonic area is filled with the BIP39 mnemonic words.

**Comment by andronoob** [comment]
The seed was derived from the mnemonic words through one-way hash function (2048 rounds of PBKDF2), therefore, it's impossible to convert a seed back to mnemonic words.
