### ISSUE TITLE
Ethereum private key incorrect

### ISSUE THREAD

**Issue by iancoleman** [iancoleman/bip39#399]
Continuing from https://github.com/iancoleman/bip39/issues/395#issuecomment-578420534

> I get the expected ETH address in standalone (without any Chrome or Brave issues) from my 12 word seed but it's giving me an incorrect private key

My manual tests (`abandon abandon ability` `m/44'/60'/0'/0/0`) give

0.3.11
Address 0xe5815d
Public Key 0x03e723e
Private Key 0x8f253078

0.4.0
Address 0xe5815d
Public Key 0x03e723e
Private Key 0xL21y1q

Private key is not matching.

To do:

* Find reason for change in private key and fix
* Change network tests to check all table values, not just address

**Comment by iancoleman** [comment]
It's using the bitcoin privkey WIF string instead of the ethereum hex encoded privkey.

Need to change

https://github.com/iancoleman/bip39/blob/927450e169e15e31b8f402c78a016cac47fc582d/src/js/index.js#L1137

to

`privkey = libs.ethUtil.bufferToHex(keyPair.d.toBuffer())`

I'll add this change and release asap (once the tests are all updated, a lot of extra test data to add so will take some time).

Thanks for bringing this to my attention @pieman64 and @PaulUD

**Comment by PaulUD** [comment]
Cheers @iancoleman

**Comment by iancoleman** [comment]
See https://github.com/iancoleman/bip39/commit/dd496c82c10ddd9612c80c70b4a21e05f2720624

Fix released in 0.4.2

**Comment by spyhandler** [comment]
Thank you. As of my understanding, anyone who would have generated a seed within 0.3.11 could have used it without any problems on Ledger / Trezor, but if he tried exporting private keys through the tool, he would have freaked out because of the messed up private key?

BR.

**Comment by PaulUD** [comment]
@spyhandler almost. **0.3.14** was fine.
