### ISSUE TITLE
Add BNB Coin

### ISSUE THREAD

**Issue by leocodeninja** [iancoleman/bip39#407]
Can you add BNB addresses?

Thanks!

**Comment by iancoleman** [comment]
Please ask BNB community to submit a pull request adding this coin.

**Comment by mvillalba** [comment]
Would you accept this from someone else? I'll take a crack at it if so.

I was just playing with this and I don't think it'd be too hard to add. Setting the coin to ETH and the correct derivation path in the BIP32 tab will give you valid priv/pub key pairs (that TrustWallet will accept, resulting in the expected BNB addresses). Basically, all you are missing is a pubkey->BNB address function and some glue code.

**Comment by iancoleman** [comment]
Usually most altcoin additions are accepted, feel free to submit a PR. The main thing that prevents it or slows it is if there are significant new external libraries needed.
