### ISSUE TITLE
BIP85 support

### ISSUE THREAD

**Issue by kirillkovalenko** [iancoleman/bip39#424]
Please add [BIP85](https://github.com/bitcoin/bips/blob/master/bip-0085.mediawiki) entropy derivation support.

**Comment by hoganri** [comment]
@iancoleman there is now support for this in node https://github.com/hoganri/bip85-js or via npm - https://www.npmjs.com/package/bip85-js

**Comment by AndreasGassmann** [comment]
I opened a [PR](https://github.com/iancoleman/bip39/pull/454) that adds this feature.

![bip39-bip85](https://user-images.githubusercontent.com/680814/98446102-a7eb9580-211b-11eb-9b45-6c1f43021d70.png)

When I started working on this, @hoganri's library wasn't available, so I created my own, which I also used in this PR:
https://github.com/AndreasGassmann/bip85
https://www.npmjs.com/package/bip85

**Comment by AndreasGassmann** [comment]
This was just merged! 🎉 

It will be available in the next release.

**Comment by kirillkovalenko** [comment]
@AndreasGassmann Very nice. Thank you for your effort!

**Comment by jsarenik** [comment]
@kirillkovalenko Please close this issue. Thanks.
