### ISSUE TITLE
Please add Waves Coin

### ISSUE THREAD

**Issue by abhijitrath791** [iancoleman/bip39#432]
All details below about waves config

"derivationPath": "m/44'/5741564'/0'/0'/0'",
        "curve": "ed25519",
        "publicKeyType": "curve25519",
        "explorer": {
            "url": "https://wavesexplorer.com",
            "txPath": "/tx/",
            "accountPath": "/address/"

**Comment by abhijitrath791** [comment]
Derivation path BIP44 m/44'/5741564'/0'/0'/0'

**Comment by iancoleman** [comment]
Please ask the waves coin community to submit a pull request.
