### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by maltokyo** [iancoleman/bip39#440]
On any mac or linux system, I use this to generate 256bit binary string.  Any thoughts or comments on whether this is secure enough as the entropy input (using in offline computer) for this tool?

`head -100000000 /dev/urandom | LC_ALL=C tr -dc '0-1' | head -c 256`

**Comment by iancoleman** [comment]
Sounds fine but I am no expert in secure random so this is just my opinion and it may not be appropriate for your needs. /dev/urandom depends on certain factors like how much entropy has been gathered by the operating system. eg fresh start of a live distro may not have much entropy.
