### ISSUE TITLE
Electrum seed gives invalid mnemonic error 

### ISSUE THREAD

**Issue by Kyzcreig** [iancoleman/bip39#448]
When I make a new Segwit (bech32) wallet in Electrum the seeds it generates are not considered valid. Is that expected behavior?

Screenshot:
![image](https://user-images.githubusercontent.com/9063726/96085851-43b81780-0e76-11eb-92a7-078e64b64af8.png)
![image](https://user-images.githubusercontent.com/9063726/96085902-56325100-0e76-11eb-9195-be87d49b60d0.png)

Seed:
angry couple quit penalty source six all same tattoo squeeze mean today

**Comment by jsarenik** [comment]
Yes, that is know. Electrum uses its own way to produce a seed which contains some extra information. Will link to documentation when I find it.

**Comment by jsarenik** [comment]
https://electrum.readthedocs.io/en/latest/seedphrase.html says:

> Starting with version 2.0, Electrum seed phrases include a version number, whose purpose is to indicate which derivation should be followed in order to derive private keys and addresses.

**Comment by jsarenik** [comment]
When you click `Options` button (in the screenshot you posted earlier) and check `BIP39 seed` then you can paste the seed generated by https://iancoleman.io/bip39/

**Comment by Kyzcreig** [comment]
I see. Thank you. 

1) Are there any plans to make this tool compatible with Electrum's seed format? What would that take?
2) I suppose I can generate a BIP39 seed and then import this into Electrum and it will work as desired, is that right?

**Comment by Kyzcreig** [comment]
2.1. Won't that be insecure though, to use a seed generated from this tool? Is there a more secure way to generate a BIP39 seed offline?

**Comment by jsarenik** [comment]
> 2. I suppose I can generate a BIP39 seed and then import this into Electrum and it will work as desired, is that right?

Yes.

**Comment by jsarenik** [comment]
> 2.1. Won't that be insecure though, to use a seed generated from this tool? Is there a more secure way to generate a BIP39 seed offline?

This tool can be used offline.

**Comment by iancoleman** [comment]
Thanks for your help with this @jsarenik

**Comment by Kyzcreig** [comment]
Thank you. I have one last question, how random is the mnemonic generator - how many possibilities can be generated - how feasible is it to brute force my generated seed?

**Comment by iancoleman** [comment]
One of many answers to this:
https://old.reddit.com/r/Bitcoin/comments/jdnuvy/what_is_to_stop_some_hacker_cranking_out_24_word/

In relation to the specific implementation in this tool, have a look at https://iancoleman.io/bip39/#entropy-notes

It's not feasible to brute force mnemonics >12 words

**Comment by Kyzcreig** [comment]
This answers my question exactly. 
Thank you so much.

**Comment by marek22k** [comment]
How can I convert a electrum seed to a "normal" seed?

**Comment by cryptopivot** [comment]
> 

Electrum seed is a "normal seed".  However, Electrum standard wallet uses a different derivation path than most other hd wallets today.

I think what you are confused with is derivation paths,  as an example m/49'/0'/0'/
