### ISSUE TITLE
24th Word different to SeedPicker

### ISSUE THREAD

**Issue by darrenahunter** [iancoleman/bip39#461]
Hi - I am using  the generate function of  the page to generate 24 words (all else is default - ie. a clean loaded html page).
I copy the first 23 words into the SeedPicker 24th Word generator page (https://seedpicker.net/calculator/last-word.html) and generate the 24th word.
It is different to the original 24th word.

From my understanding the 24th word is a checksum of the first 23 words so should be consistent ?
Am I missing something here?
I have also asked on the SeedPicker contact.

Any help would be great

thanks
Darren

**Comment by iancoleman** [comment]
Not all 11 bits of the last word form the checksum. So there are multiple last words that would result in a valid checksum.

From https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#generating-the-mnemonic

> First, an initial entropy of ENT bits is generated. A checksum is generated by taking the first `ENT / 32` bits of its SHA256 hash.

**Comment by darrenahunter** [comment]
many thanks Ian
that makes sense to me - the SeedPicker guys also responded and (obviously taught me the same thing) they always take the same word for consistency in the page. also makes sense so if a user enters the same 23 words they will get the same 24th word.
