### ISSUE TITLE
Desktop App

### ISSUE THREAD

**Issue by trymeouteh** [iancoleman/bip39#465]
Please make this into a simple electron desktop app which can be downloaded on Windows, Mac and Linux (AppImage, Debian Repo, Arch Repo) with a SHA256 signatures to ensure it is secure. This way no need to trust the website if it is compromised and can be used offline.

**Comment by iancoleman** [comment]
Download it from https://github.com/iancoleman/bip39/releases and use the html file on any offline computer with a browser.

There's also signed sha256 hashes there. No need for electron.
