### ISSUE TITLE
Binary padding bug

### ISSUE THREAD

**Issue by jase1981** [iancoleman/bip39#49]
Hi! I've been trying to manually go through process of creating mnemonic from provided entropy. It didn't work as expected, because there is a bug in function setMnemonicFromEntropy():
```
    for (var i=0; i<256-bits.length; i++) {
        bits = "0" + bits;
    }
```
If 2 or more leading zeroes are needed, the loop skips one, because both i and bits.length are incremented at the same time.

**Comment by dooglus** [comment]
How about writing it like this instead:

    while (bits.length < 256) bits = "0" + bits;

**Comment by iancoleman** [comment]
Thanks for this @jase1981, good catch.
