### ISSUE TITLE
Integration for Cardano

### ISSUE THREAD

**Issue by michaelhuber1937** [iancoleman/bip39#491]
I want to ask if there are any plans to integrate key-derivation for Cardano (ADA)?

I really love the tool but unfortunately Cardano is not listed in the COIN-dropdown-menu.

**Comment by audstanley** [comment]
I'm not the developer for this project, but based on looking at some of the cardano source code... I'm not sure you can generate a wallet without being connected to the cardano blockchain. Evan ADA Light just makes API calls. I wanted to write some GoLang code to be able to generate cardano wallets, but since the protocol is written in Haskell... It's a little to thick for me to deconstruct. 😊 Maybe a cardano developer could shed some light on all this.  It's kinda cool that one might be dependent on the blockchain in order to secure their funds... Also a little scary.

**Comment by michaelhuber1937** [comment]
@audstanley Thanks for your answer! I have done some deeper research and IT IS possible to generate a complete offline paper-wallet, even with a passphrase. This is possible via Yoroi which is basically a Browser-Extension/HTML-Website. I have tested this successfully and the Yoroi-Wallet is generating a 2-page paper-wallet as PDF. What's annoying that this paper-wallet is generating maximum 5 addresses and these addresses have legacy format (byron-address-format instead of the current shelley-format).

So IT IS possible to derive addresses from a given seed (+ optional passphrase).

Sometimes the crypto-space is really annoying me. Generating a wallet from a seed with a passphrase should be one of the basic-elements of a crypto-currency! This stage of implementation is sooo far away from being end-user-friendly that even with a degree of computer-science in Germany it's hard to understand certain topics in a short time. This does not help in any way to get mass-adoption.

What I don't understand: Why the hell would someone use Adalite which is an Online-Website to have a wallet. I would never enter a seed on a website and of course not in a browser-plugin with a computer connected to the internet. Just my 2 cents.

**Comment by audstanley** [comment]
lol  @michaelhuber1937 - you beat me to it.  I was literally just watching a video on [BECH32](https://www.youtube.com/watch?v=NqiN9VFE4CU), and you're right. It will be possible... it's just crazy complicated. It's amazing that this new form of cryptographic wallets were only proposed a few years ago... and I think, eventually, these features will be standard.  Hard core safety when it comes to transferring assets is something that is a **MUST** for more widespread adoption.  If an average person misses a letter or two when sending their money, then their money doesn't just shoot into a black hole... never to return.  It's likely going to take some time for [libsodium](https://doc.libsodium.org/quickstart) to make its way into other programming languages natively.  What amazing times we live in.  I looked at Adalite's source code... and oh man... their Redis environment variables look sketchy (to me)... they likely use it for testing, but when i see that (database envs)... all i can see are **red flags**.  It's a nice idea, but if you have to be online to run the source code... no thanks.  :slightly_smiling_face:

**Comment by audstanley** [comment]
@michaelhuber1937 https://github.com/input-output-hk/cardano-addresses

**Comment by sruPL** [comment]
I would also love to see support for ADA.

**Comment by iancoleman** [comment]
Please ask the cardano community to submit a pull request.
