### ISSUE TITLE
Support for xpub of hd multisig wallet

### ISSUE THREAD

**Issue by HostFat** [iancoleman/bip39#50]
It would be cool to being able to retrieve all the public keys and addresses from an xpub of a multisig hd wallet like Copay.

**Comment by iancoleman** [comment]
Thanks for this.

Please have a read of the existing (closed) issues regarding this https://github.com/iancoleman/bip39/issues/42
https://github.com/iancoleman/bip39/issues/40

and the commit that provides the feature

https://github.com/iancoleman/bip39/commit/ba3cb9ecae2667e98af71f5b38a862ba604e8e1c

If you have any specific information or suggestions that would help improve this feature please add some detail so the tool can be improved.

**Comment by HostFat** [comment]
The addresses generated from an xpub of a **multisig** hd wallet, aren't multisig. (I just tried)

So, maybe, all the xpubs from the other cosigners are needed to generate them.

You can just try to generate a multisig wallet from Copay, and then from Options -> Advanced -> Wallet information, you will find all the xpubs from all the cosigners.

**Comment by iancoleman** [comment]
Ah yes I missed the crucial words multisig / copay. Been a busy few days for me.

This is a very good idea but entails a lot of user experience complexity. I'll think about how to make a clean UI and get back to you. Suggestions welcome.

My initial feeling is a separate tool may be clearer, but will think on it. It would certainly be useful.

**Comment by HostFat** [comment]
Even Electrum support multisig wallet, but it has a different format from the one used on Copay.

I think that your tool is already for advanced users, so I don't think that adding a multisig section somewhere will make it worse :)

**Comment by iancoleman** [comment]
Having spent a long time thinking over this, I opted for a separate tool that works easily with the output of this tool.

https://iancoleman.github.io/multisig/

The feature for directly supporting xpub and xprv keys is still under development; see https://github.com/iancoleman/multisig/issues/1

As an interim alternative, use hex public keys or wif private keys from the address table in this tool.

The amount of additional complexity for multisig is quite significant and didn't fit well into the ux of this tool.
