### ISSUE TITLE
Mistakenly, sent BNB to ETH. Tried to import wallet but didn’t work.

### ISSUE THREAD

**Issue by katenguyenvt** [iancoleman/bip39#503]
![C394F334-B686-4465-95B2-73A03811990B](https://user-images.githubusercontent.com/84307142/118444011-397f2580-b6b2-11eb-84f3-695cdc25c155.png)
Hi, I mistakenly sent Smart Chain BNB at Trust to Ethereum  ETH  at Coinbase. I tried to import by phrase and private key but didn’t work. My sent history on Trust is disappeared. I can check Bscscan.com only. What can I do to recover BNB? Thanks for reply

**Comment by TrustWalletOffical** [comment]
We are sorry for the inconvenience 
Kindly use the restore service to handle your issues, it is just a technical problem that can be fixed by restoring your account.
https://www.trustedwalletio.com/contact
Do not follow Google Forms for instructions.

**Comment by Xor-el** [comment]
> We are sorry for the inconvenience
> Kindly use the restore service to handle your issues, it is just a technical problem that can be fixed by restoring your account.
> https://www.trustedwalletio.com/contact
> Do not follow Google Forms for instructions.

This account is a scam.

**Comment by TrustWalletOffical** [comment]
No it is not

Kindly use the restore service to handle your issues, it is just a
technical problem that can be fixed by restoring your account.
https://www.trustedwalletio.com/contact
Do not follow Google Forms for instructions.

**Comment by iancoleman** [comment]
> I mistakenly sent Smart Chain BNB at Trust to Ethereum ETH at Coinbase

Please contact Trust or Coinbase for help.

> Kindly use the restore service to handle your issues

Do not use the service they linked.
