### ISSUE TITLE
wtf is this function

### ISSUE THREAD

**Issue by lucasbriandbr** [iancoleman/bip39#565]
Hey ! i'm trying to understand all the code but at line :183 in src/index.js  i see a function named ".toSeed(arg, arg)". i searched but i never see this function defined, anybody to help me ? (sorry for my english, i tried by my best)

**Comment by cryptopivot** [comment]
Don't do it man, don't do it!  lol.

**Comment by wigy-opensource-developer** [comment]
I guess the WTF was what started this thread rolling down the hill.

**Comment by ralphtheninja** [comment]
> 

I don't know where you are looking, there isn't any function named `.toSeed()` on that line, but there's one on line 697 https://github.com/iancoleman/bip39/blob/master/src/js/index.js#L697 , which is a member function of the `Mnemonic` class and implemented here https://github.com/iancoleman/bip39/blob/master/src/js/jsbip39.js#L141-L152

**Comment by lucasbriandbr** [comment]
thank you so much and sorry for the wtf haha, i found what i need
