### ISSUE TITLE
Last word instead of "Invalid mnemonic"

### ISSUE THREAD

**Issue by robertodeavila** [iancoleman/bip39#585]
Is there any possibility for the standalone version (bip39-standalone.html) to display the last word instead of the message "Invalid mnemonic", when only one word is missing?
Facilitating the creation of offline wallets using old android phones disconnected.
Making it possible to choose the 23 words by lot and the last one would be calculated on an old cell phone.
The github.com/merland/seedpicker does not run on cell phones offline, the "seedpicker" requires a computer.

**Comment by cryptopivot** [comment]
https://github.com/ZenGo-X/mnemonic-recovery
