### ISSUE TITLE
Split mnemonic issue

### ISSUE THREAD

**Issue by cesarmassri** [iancoleman/bip39#593]
Split mnemonic for a 12-word leaves 4 words hidden. It is possible to brute-force them.

The same problem occurs for a 15-word mnemonic. For 24-words is ok.

Source: https://medium.com/@johncantrell97/how-i-checked-over-1-trillion-mnemonics-in-30-hours-to-win-a-bitcoin-635fe051a752

**Comment by wigy-opensource-developer** [comment]
I have just checked the live application and it clearly says `Time to hack with only one card: 109 seconds` with a red font under the split cards. Is there something else the application could do?
