### ISSUE TITLE
Need help about setHdCoin(); value

### ISSUE THREAD

**Issue by koraycoding** [iancoleman/bip39#617]
Hello. I'm trying to add a new coin and i have all the information except one thing.

What's the **setHdCoin();** value? How do i find this value in coin's source code?

Relevant code is mentioned in src/js/index.js file. For example

`{  
            name: "XXX - xxxcoin",  
            onSelect: function() {  
                network = libs.bitcoin.networks.xxxcoin;  
                setHdCoin(1);
            },
        },
`

Thank you very much for the help.

**Comment by iancoleman** [comment]
The value for setHdCoin comes from the BIP44 registered coin types:
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

It sets the 'coin' value for BIP44/49/84 tabs

**Comment by koraycoding** [comment]
Thanks for the quick reply.

What value should i use if the coin is not on that list? It's a bitcoin fork.
