### ISSUE TITLE
Pressing Return while cursor is in the BIP85 Index field causes the page to generate entirely new random BIP39 Mnemonic

### ISSUE THREAD

**Issue by 2oh1** [iancoleman/bip39#634]
This seems like it must be a bug.

Pressing the "return" key when the cursor is in the BIP85 Index field causes the page to generate an entirely new random BIP39 mnemonic.  At first, I was confused because the BIP85 child key kept changing, and then I realized I'd pressed return, which unintentionally forced the entire page to generate a new BIP93 mnemonic and recalculate.

Is it possible to add a checkbox to enable/disable the "Generate a random mnemonic" function?

**Comment by ancjf** [comment]
This raises a new issue: clicking the "GENERATE" button in Safari does not produce the mnemonic words.
