### ISSUE TITLE
Is Dice6 entropy calculated wrong?

### ISSUE THREAD

**Issue by ZenDragonX** [iancoleman/bip39#636]
Hello, when calculating dice rolls for 100 rolls of the dice it is saying that 100 rolls is only 169 bits of entropy.  However log2(6^100) = 258.  Not 169.

**Comment by iancoleman** [comment]
See [entropy.js L26-29](https://github.com/iancoleman/bip39/blob/e2fdc5b9420fe45a255776f0caa6df8b0baf4a2c/src/js/entropy.js#L26-L29) and [this comment](https://github.com/iancoleman/bip39/issues/435#issuecomment-701170757) in #435 to understand why a single dice roll is less than log<sub>2</sub>(6) bits of entropy (whole conversation in 435 is worth reading, the topic definitely evaded my own intuition and is pretty fascinating).

**Comment by brianddk** [comment]
I'm siding with @ZenDragonX  on this one.

Using the DICE entropy string "123456123456" notice the filtered entropy goes to "123450123450".  So ONLY 6 wraps?  If the symbols are `{1,2,3,4,5,6}` then 6 should be valid.  Perhaps filtered base6 should read "012345012345" but wrapping ONLY 6, while leaving the rest unchanged seems weird to me.

You can spot-check this against : https://github.com/Coldcard/firmware/blob/master/docs/rolls.py to show the "wrapping 6 bug".  If you try "1234512345" on both you get:

^(tool aim drum remain amazing present strike tattoo fox guilt vessel protect salute forward galaxy hidden long chunk humor lumber upset news build behave)

Subtle... but I really do think this is bugged whenever `6` shows up in the entropy string.

**Comment by wigy-opensource-developer** [comment]
Good thing is you still have 6 symbols however you label them, so the Shannon entropy has to be the same.
