### ISSUE TITLE
Add balance option 

### ISSUE THREAD

**Issue by aponxp** [iancoleman/bip39#647]
![Capture](https://github.com/iancoleman/bip39/assets/76506958/8d8c2b41-32b3-4b4d-89d1-dec812da6eb6)

Add here ETH / BNB / Coin  Balance option 

path  |  Balance | Address |  Public Key | Private Key

Thanks All Developers Sir.

**Comment by wigy-opensource-developer** [comment]
This tool is meant to be used on an offline computer. That is why you can download the whole tool as a standalone .html file. On the other hand, you can find many online (hot) wallets for your purpose.

**Comment by aponxp** [comment]
Hello sir, I know it used on an offline computer. I thought that's why I asked. I'm new to these, so don't mind my questions. I think tools are incomplete without balance option. I think if one uses this tool online then the balance will show. What does it take to do? can its possible to add a balance option ?

Thanks sir for response

**Comment by iancoleman** [comment]
The tool is intended to be used offline. It's a key management tool, not a wallet. Balance is not a desired feature of this tool.

Previous related response: https://github.com/iancoleman/bip39/issues/6#issuecomment-244655630
