### ISSUE TITLE
why changing Derivation Path changes BIP32 Root Key

### ISSUE THREAD

**Issue by ccp42** [iancoleman/bip39#648]
Dear Ian,
I would like to know why, having a generated wallet with a seed phrase, then with the derivation path of BIP44 has the root key but this changes when choosing BIP49, BIP84...
Shouldn't the root key remain unchanged with the same seed phrase no matter the changes in the derivation paths?
Thank you.
derivation BIP44:
![1](https://github.com/iancoleman/bip39/assets/105308041/0e087a3a-e6b3-4d60-82c7-588dccd28c01)
derivation BIP49:
![2](https://github.com/iancoleman/bip39/assets/105308041/18de872d-ad4c-43e8-984f-acb9a3e997b7)

**Comment by iancoleman** [comment]
SLIP0132 explains the reason:
https://github.com/satoshilabs/slips/blob/master/slip-0132.md#motivation

Happy to elaborate if there are more specific questions.

**Comment by ccp42** [comment]
Thank you for answering. I am going to study it :D
