### ISSUE TITLE
Generate mnemonic+passphrase from bip39 seed

### ISSUE THREAD

**Issue by Engelberg** [iancoleman/bip39#68]
Specifically, I have a mnemonic, and I'd like to convert it into a mnemonic+passphrase that yields the same seed.

Your tool allows me to go from the mnemonic to bip39 seed.  What I'd like to do is now go the other direction, entering in the bip39 seed and a passphrase, and see the new mnemonic that combines with the passphrase to yield the same seed.

Is there any way to do that?

**Comment by iancoleman** [comment]
Unfortunately not.

[`mnemonic.toSeed` calls pbkdf2 / hmacSHA512](https://github.com/iancoleman/jsbip39/blob/master/jsbip39.js#L139) to generate the seed, which means it's not reversible from seed to mnemonic.

See also [issue 22](https://github.com/iancoleman/bip39/issues/22) and [BIP39 from mnemonic to seed](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#from-mnemonic-to-seed).
