### ISSUE TITLE
Improve release, update practices

### ISSUE THREAD

**Issue by SilentCicero** [iancoleman/bip39#72]
Hi Ian, first-off great tool, this thing is amazing!

I'd like to bring up a few points on release and update practices.

1. Improve Release Practices by using the Github "Release" features, this way I can get a solid ZIP release of the tool, along with an MD5 hash of the ZIP, release reference number
2. Everytime an update is made to the tool, I think it should be noted in a `CHANGE_LOG.md` file, that way we know if a bug is created in the tool, we can diagnose more clearly and quickly what it is
3. You may want to accompany the release of any new updates with a Tweet, and potentially post the new release number and MD5 hash with it

Thanks so much for writing this tool @iancoleman! I would like to recommend it as a way to generate/manage keys for Ethereum, but I want to see some basic release and update practices maintained before I can do this.

As well, I may be able to have the tool professionally code-frozen and audited (I would pay/raise the money for that). That way we have a solid copy that works and is audited, with a specific release and MD5 hash attached.

**Comment by iancoleman** [comment]
Thanks for this.

**Github Release Feature** - good idea, I'll start using this

**Change log** - also a good idea, I'll start one for this project. The commit history is a good indication of the changes, but a changelog is useful too.

**Twitter** - Not sure about the benefit of a tweet for every release. Can you please elaborate?

**MD5** - Any particular reason for wanting an MD5 hash for the release? [MD5 has been broken](http://www.mscs.dal.ca/~selinger/md5collision/).

Feel free to fork to a specific commit and have it frozen / audited. I don't think specific release practices are needed for this to happen.

All the same, the suggestions are good ones and I'll look into implementing them. Thanks for taking the time to submit this.

**Comment by SilentCicero** [comment]
Sorry, maybe not MD5 I prefer keccak256 (I'm an Ethereum nut).

I'm writing a doc for the Ethereum community that heavily uses this tool. I'd like a clear verification path from github download, along with version and code freezing.

This will be used to generate cold wallets. Dont worry, I have everything in there about safe entropy, safe computing, checking backups and recoveries and recommended hardware.

It's a very elaborate document. lol.

I would love to ask you some more questions in person, how can I contact you?

**Comment by SilentCicero** [comment]
Also, I believe github does MD5 or sha hashing when you upload or create the ZIP.. I think that's why I thought MD5.. anyway, try it out lets see what you get =D

**Comment by iancoleman** [comment]
> publicly share the hashes of the latest releases

See https://twitter.com/bip39tool

> can you hex prefix the Ethereum public and private keys when generated

See https://github.com/iancoleman/bip39/commit/d0239db48c485dc912bb41ef33c2f5b4fdf32b5e

> Improve Release Practices by using the Github "Release" features

See https://github.com/iancoleman/bip39/releases

> Everytime an update is made to the tool, I think it should be noted in a CHANGE_LOG.md file

See https://github.com/iancoleman/bip39/blob/master/changelog.md although I think the git commit history is a much more useful log of changes.

>  how can I contact you?

You can find my contact details in the repository log

How does this release process look? It has versioning, github releases, changelog, twitter announce with hash. I'm used to working on larger projects with continuous integration so am happy for feedback on this manual release process.

**Comment by SilentCicero** [comment]
@iancoleman awesome start!

Okay, I would see about the release, I think you can up your game on formatting, checkout this repo/project release:

https://github.com/kvhnuke/etherwallet/releases

Something like this is very straight forward.

Thanks for throwing in the change log, it really does help for readability.

Twitter is often overkill, but in my mind a nice addition just to publicly state hashes of the tool.

Thanks so much dude, looking great. I would check out the release formatting feature.

**Comment by iancoleman** [comment]
Ah yes, I see now that there's a difference between a git tag and a github release. I've created a release for 0.1.0
The main thing I felt was missing was a direct download for bip39-standalone.html which is now part of the release.

https://github.com/iancoleman/bip39/releases/download/0.1.0/bip39-standalone.html

**Comment by SilentCicero** [comment]
@iancoleman looking good, I would throw the hash in the release notes as well, just makes it easier to compare with hash on twitter.

Dude, great stuff. I will pay to have 1.0 audited, I'll let you know what I can find =D
