### ISSUE TITLE
signature not available?

### ISSUE THREAD

**Issue by Golddouble** [iancoleman/bip39#83]
When we download a software like electrum we also get a signuture. So we can check if the file is still in the original condition:
![elecrum signature](https://user-images.githubusercontent.com/13977359/28241563-47880d98-6997-11e7-911d-292102acf0b6.PNG)

Question: Don't you offer a signature to your standalone file? Shouldn't we be able to check if it is in the original condition?

**Comment by iancoleman** [comment]
I agree a signature will be useful to include with releases.

I think a combination of uploading a signature with the release:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

and using signed tags in git itself:
https://help.github.com/articles/signing-tags-using-gpg/

**Comment by Golddouble** [comment]
Thank you.
Yes, just any signature that we can verify with https://www.gpg4win.org/features.html would be helpful.

**Comment by iancoleman** [comment]
Signatures will now be included with releases, eg [v0.1.2](https://github.com/iancoleman/bip39/releases/tag/0.1.2) is now signed using [my gpg key](https://iancoleman.github.io/B89A317AB798EB23.txt).

Thanks for the suggestion.

**Comment by Golddouble** [comment]
Wow, thank you.
