### ISSUE TITLE
Add full list of coin types

### ISSUE THREAD

**Issue by mocmocamoc** [iancoleman/bip39#86]
As of v0.2.0 it isn't possible to manually change the "Coin" field in the BIP44 derivation path, but the dropdown of available coin types contains only a small subset of those defined in [SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md). Most notably, Bitcoin Cash (145) isn't present although it is currently useful for people who are splitting that currency away from their Bitcoin addresses.

Please could you add Bitcoin Cash (145),  and ideally all the types defined in SLIP-0044 if possible.

**Comment by iancoleman** [comment]
Thanks for this. You make a good point.

The difficulty with adding all SLIP-0044 coins is they need to have their network parameters defined to work with this tool, not just the BIP44 coin field (see [bitcoinjs-extensions.js](https://github.com/iancoleman/bip39/blob/master/src/js/bitcoinjs-extensions.js)). I'm not sure where to get these parameters for most coins (although for bitcoin cash this is obviously not a problem).

I see two reasonable courses of action:
* remove readonly from the coin field
* add bitcoin cash to the list of coins and keep coin field readonly

I'm leaning toward the second option. Modifying the coin field value isn't really something that should be done, and if that degree of customisation is desired by end users they should use the bip32 tab with a manually configured derivation path.

**Comment by iancoleman** [comment]
Bitcoin Cash has been added, see https://github.com/iancoleman/bip39/commit/daab55dc613a1eef22463356eba1a742cb814cb2

I'm inclined to keep the coin field readonly, since there's always the bip32 tab with manual derivation path for advanced users.

Thanks for the suggestion.
