### ISSUE TITLE
Bitcoin Cash address on tool do not match to pre-fork addresses

### ISSUE THREAD

**Issue by avibrazil** [iancoleman/bip39#88]
I have pre-fork Bitcoin funds that are now available as Bitcoin Cash too.

But using same mnemonic with m/44'/145'/0' derivation path gives me completely different addresses. I was expecting same addresses where I can confirm I have funds in BTH/BCC.

Thank you

**Comment by iancoleman** [comment]
I couldn't reproduce this.

Can you provide more information?

Steps I took to get the same address:

* Generate a random mnemonic using v0.2.1
* Select Bitcoin Cash
* Record the mnemonic and first address in the list
* Load v0.1.2 (from before bitcoin cash)
* Paste the mnemonic
* Manually change the coin to 145 on the bip44 tab
* Observe the first address are the same

Please provide more detail.

**Comment by avibrazil** [comment]
The problem is not between versions but between coin types.

I gave it some thoughts. The coin number is a convention. I can't expect that coin 145 (BTH) will give me same addresses as coin 0 (BTC). So in the post-fork transition, I'll have to use m/44'/0' addresses with BTH to reach my funds on the new coin and then transfer them to m/44'/145' addresses.

I think we can close this.
