### ISSUE TITLE
Multibyte pubKeyHash - zcash

### ISSUE THREAD

**Issue by alkley** [iancoleman/bip39#94]
When trying to add ZEC I encountered an error in believe in bitcoinjs which enforces pubkeyhash as a UInt8 and therefore doesn't allow values great than 255. ZEC uses 7352 (0x1CB8).

See:
https://github.com/trezor/trezor-common/blob/5f7a1a7a5a4311fd71ed113624dd1d0fe9e72ff5/coins.json#L179

This is a fork of this project but with an older version of bitcoinjs:
https://github.com/Coinomi/bip39/blob/58a3bb9680a0291a2bc57f3fcc1c7d22e3ab2259/src/js/bitcoinjs-extensions.js#L863

To reproduce adding to bitcoin-extensions.js:

    bitcoinjs.bitcoin.networks.zec = {
      messagePrefix: "unused",
      bip32: {
        public: 0x0488b21e,
        private: 0x488ade4
      },
      pubKeyHash: 0x1cb8,
      scriptHash: 0x1cbd,
      wif: 0x80,
    };

throws TfPropertyTypeError for property pubKeyHash.

**Comment by iancoleman** [comment]
Thanks for this. I'm following it up with bitcoinjs-lib

https://github.com/bitcoinjs/bitcoinjs-lib/issues/865

**Comment by iancoleman** [comment]
I'm not willing to fork / modify bitcoinjs-lib to support this feature. I've subscribed to the relevant issue in bitcoinjs-lib, so when this feature is ready I'll look into addressing this issue.

**Comment by avibrazil** [comment]
Coinomi has a tool that seems to be derived from this one:

https://coinomi.com/recovery-phrase-tool.html

It supports many many coin types. Maybe support for more coin types can be borrowed from their JavaScript source code.

**Comment by iancoleman** [comment]
Closed via https://github.com/iancoleman/bip39/pull/212
