### ISSUE TITLE
error trying to generate addresses from xpub with hardened derivation

### ISSUE THREAD

**Issue by dooglus** [iancoleman/bip39#95]
I see you have your site detect whether there's any single quotes in the derivation path and give an appropriate error if there is when all we have is an xpub, but if I try to derive addresses from an xpub using a derivation path of "m/0" but with "Use hardened addresses" checked, there's no error message other than in the javascript console.

Ideally the same orange error box would pop up as when I put a single quote in my derivation path.

**Comment by iancoleman** [comment]
Good catch, thanks for reporting.

See https://github.com/iancoleman/bip39/commit/b18eb97ae367e7eaa276a8ddbaaca3e158cf153d which will be included in the next release.
