### ISSUE TITLE
ETH Mnemonic Phrase generated in Spanish does not work in myetherwallet.com/#view-wallet-info

### ISSUE THREAD

**Issue by ncsolar** [iancoleman/bip39#97]
I tried using bip39 to generate a Mnemonic Phrase in Spanish but it did not work in myetherwallet.com, selecting English works as expected

Thanks

**Comment by iancoleman** [comment]
Thanks for this.

Can you please clarify what is meant by 'did not work'. What was the expected result? What happens instead?

I tried importing a mnemonic from a language other than English and the Unlock button to load the mnemonic would not show in myetherwallet. This suggests to me that myetherwallet doesn't support any other languages for mnemonics besides English, but I'm not familiar with the feature set of myetherwallet so please confirm that I've understood the issue correctly.

I had a brief look through the code for myetherwallet and can't see anywhere the language / wordlist for the mnemonic being set to anything other than English, even though there is other wordlists in the code. I think best if you raise an issue with myetherwallet also just to clarify.

**Comment by ncsolar** [comment]
Yes that is the issue, the Unlock bottom to load the wallet is never available, sorry for not being clear.

I also noticed that if I use the QR code in bip39 to capture the words, words like "álbum" would be "album" with no "´"

**Comment by iancoleman** [comment]
This is something that will need to be raised with myetherwallet.

Good observation about the qr code missing accents, I've opened a separate issue for tracking that. See https://github.com/iancoleman/bip39/issues/101

**Comment by Zwilla** [comment]
yes it is a myetherwallet problem, I will publish a version which will work on 
* https://mytokenwallet.com
also will make a pull request on official bip39 for auto detection of the wordlist

**Comment by Zwilla** [comment]
I will let you know that we have **finished our work** and now all languages will be detected by our walltet at https://mytokenwallet.com and watch this video here: https://youtube.com
