### ISSUE TITLE
entropy field suggests it accepts multiple sources

### ISSUE THREAD

**Issue by noun** [iancoleman/bip39#99]
The language used in the entropy field gave me the impression one could enter a deck of cards, then the outcome of tossing coins, etc, all as sources of entropy. I thought it was only advisory, as in "these are great sources of entropy - as opposed to keyboard mashing".

1. Am i right in thinking the "filtered" result may dangerously discard entropy, e.g., dropping "q", "k", etc., from the initial entry of cards, once a run of 1's and 0's changes the interpretation of what has been entered?

2. Is the point of the filtered result to be able to interpret what has been entered and then estimate how many bits of entropy have been provided?

Why not accept any blob of text as a source of entropy, and leave it up to the advanced user to interpret how much entropy has been used?

**Comment by iancoleman** [comment]
Thanks for raising this.

> The language used in the entropy field gave me the [incorrect] impression...

The language can be updated so it gives the correct impression. Please let me know what would be appropriate language so this misconception doesn't happen in the future.

> Am i right in thinking the "filtered" result may dangerously discard entropy

Yes, the filtered result discards entropy. No, this is not dangerous.

> Is the point of the filtered result to be able to interpret what has been entered and then estimate how many bits of entropy have been provided?

Yes, but perhaps reworded as '... what has been *correctly vs incorrectly* entered ...'

> Why not accept any blob of text as a source of entropy, and leave it up to the advanced user to interpret how much entropy has been used?

This is essentially a brainwallet, which is not secure.

Advanced users understand why the entropy system is restricted the way it is. Opening it further makes it worse for all users.

I appreciate you raising this issue and if the wording can be improved it'd be good to know your thoughts on what that might look like.

Might also be worth reading [the history of this feature](https://github.com/iancoleman/bip39/issues/21) for further clarification of the design.

I'm [still open to increasing the set of entropy character sets](https://github.com/iancoleman/bip39/issues/79) but don't want to weaken the design of the feature for non-advanced users.

**Comment by noun** [comment]
I will try to read #21 soon - my apologies if it speaks to some misunderstanding on my part in the following:

> Please let me know what would be appropriate language so this misconception doesn't happen in the future.

As a stopgap, the wording could be changed to "Accepts **either** binary, ...", but this will easily go unnoticed.

Ultimately I think this should be approached programmatically. e.g., The user specifies the entropy source in a drop menu, and then rather than filtering their input, the interface displays a warning and clears all computed fields if this input no longer matches the source format.

Ideally, the user could also add multiple entropy fields of differing types.

> Yes, the filtered result discards entropy. No, this is not dangerous.

Okay, I need to think more about this and perhaps read #21 to understand.

> Yes, but perhaps reworded as '... what has been correctly vs incorrectly entered ...'

My expectation is that programs will warn me emphatically when they have detected invalid input (e.g. by halting further input), rather than smoothing over my mistake.

> This is essentially a brainwallet, which is not secure.

I see the potential for users misunderstanding the entropy field as a brainwallet passphrase field. In my opinion a high-visibility label above the field to the effect "DO NOT MEMORISE THIS INPUT" would suffice to break the association.

Additionally, if the source-type drop-menu approach is adopted, I would push for one of the entry types to be "raw". I'm still imagining users coming to the program with their own high-quality source of entropy, albeit in an unsupported source format.

**Comment by iancoleman** [comment]
> the wording could be changed to "Accepts either binary, ..."

I've changed this and will be in the next release. Thanks for the suggestion.

> user specifies the entropy source in a drop menu

This sounds good, and combined with the 'raw' entropy option it somewhat removes the responsibility from the software picking strong entropy and puts it onto the user. But, somehow, I remain unconvinced. Maybe I just dislike the entropy feature too much in the first place.

To elaborate (or rather, to rant), computers are much better at picking random numbers than people. They're faster, more accurate, and are often literally built to do exactly that. People are naturally lovers of patterns, and I really don't like having people do drudge work (like selecting the type of entropy, or really even gathering entropy *at all*) when computers are faster and better at it anyway. It seems to me one of those despicable ego things people get caught up in. Then people will claim it's a matter of trust, but if we can't rely on a purpose built rng I think there's bigger issues than being able to select and enter custom entropy. I'm not saying rng is perfect, but the tool does [detect weak rng](https://github.com/iancoleman/bip39/blob/master/src/js/index.js#L372) and won't allow generation of random mnemonics.

> Ideally, the user could also add multiple entropy fields of differing types.

I like this idea. But also think for simplicity users should pick a single strong source of entropy. I've tried to make that the easy and obvious thing to do.

> warn me emphatically when they have detected invalid input

Agreed, there could be some clearer indication that some entropy has been filtered away.

Thanks for the suggestions. I'll incorporate these changes for the next release. I enjoy exploring these issues so thanks again for your thoughts.

**Comment by iancoleman** [comment]
See
https://github.com/iancoleman/bip39/commit/ee0981f1ecc4c6e78831f538ef77396c1e4fbe91 - Detect and warn of filtered entropy
and
https://github.com/iancoleman/bip39/commit/7e6bdc498e52b57ad9777596b137473d6a7728ab - Reword entropy text to say one type, not multiple

Please continue discussion of significant changes to entropy in [#79 - Entropy should work with more character sets](https://github.com/iancoleman/bip39/issues/79)

Thanks again for the feedback and helping make this tool better.
